/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleAboutRouteImport } from './routes/$locale/about'
import { Route as LocaleAvisRouteImport } from './routes/$locale/avis'
import { Route as LocaleCatalogueRouteImport } from './routes/$locale/catalogue'
import { Route as LocaleChangelogRouteImport } from './routes/$locale/changelog'
import { Route as LocaleCheckoutRouteImport } from './routes/$locale/checkout'
import { Route as LocaleContactRouteImport } from './routes/$locale/contact'
import { Route as LocaleDevisRouteImport } from './routes/$locale/devis'
import { Route as LocaleEngagementsRouteImport } from './routes/$locale/engagements'
import { Route as LocaleEntreprisesRouteImport } from './routes/$locale/entreprises'
import { Route as LocaleFaqRouteImport } from './routes/$locale/faq'
import { Route as LocaleGarantieRouteImport } from './routes/$locale/garantie'
import { Route as LocaleGuidesRouteImport } from './routes/$locale/guides'
import { Route as LocaleHistoriqueRouteImport } from './routes/$locale/historique'
import { Route as LocaleMagasinsRouteImport } from './routes/$locale/magasins'
import { Route as LocaleMentionsLegalesRouteImport } from './routes/$locale/mentions-legales'
import { Route as LocalePanierRouteImport } from './routes/$locale/panier'
import { Route as LocalePromotionsRouteImport } from './routes/$locale/promotions'
import { Route as LocaleReclamationRouteImport } from './routes/$locale/reclamation'
import { Route as LocaleReconditionnesRouteImport } from './routes/$locale/reconditionnes'
import { Route as LocaleRepriseRouteImport } from './routes/$locale/reprise'
import { Route as LocaleReservationRouteImport } from './routes/$locale/reservation'
import { Route as LocaleServicesRouteImport } from './routes/$locale/services'
import { Route as LocaleSuiviRouteImport } from './routes/$locale/suivi'
import { Route as LocaleTarifsRouteImport } from './routes/$locale/tarifs'
import { Route as LocaleWorkAtRouteImport } from './routes/$locale/work-at'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMonCompteRouteImport } from './routes/_authenticated/mon-compte'
import { Route as AuthenticatedReviewsAdminRouteImport } from './routes/_authenticated/reviews-admin'
import { Route as ApiCronRemindersRouteImport } from './routes/api.cron-reminders'
import { Route as ApiDocsRouteImport } from './routes/api.docs'
import { Route as ApiFedapayWebhookRouteImport } from './routes/api.fedapay-webhook'
import { Route as ApiFlutterwaveWebhookRouteImport } from './routes/api.flutterwave-webhook'
import { Route as ApiHealthzRouteImport } from './routes/api.healthz'
import { Route as ApiIcalRouteImport } from './routes/api.ical'
import { Route as ApiKkiapayWebhookRouteImport } from './routes/api.kkiapay-webhook'
import { Route as ApiPushSubscribeRouteImport } from './routes/api.push-subscribe'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppGroupDashboardRouteImport } from './routes/app.group-dashboard'
import { Route as AppScanRouteImport } from './routes/app.scan'
import { Route as LocaleAppareilSlugRouteImport } from './routes/$locale/appareil.$slug'
import { Route as LocaleBlogIndexRouteImport } from './routes/$locale/blog.index'
import { Route as LocaleBlogSlugRouteImport } from './routes/$locale/blog.$slug'
import { Route as LocaleBoutiqueIndexRouteImport } from './routes/$locale/boutique.index'
import { Route as LocaleBoutiqueSlugRouteImport } from './routes/$locale/boutique.$slug'
import { Route as LocaleBoutiqueComparerRouteImport } from './routes/$locale/boutique.comparer'
import { Route as LocaleQuartiersIndexRouteImport } from './routes/$locale/quartiers.index'
import { Route as LocaleQuartiersSlugRouteImport } from './routes/$locale/quartiers.$slug'
import { Route as LocaleReparationsIndexRouteImport } from './routes/$locale/reparations.index'
import { Route as LocaleReparationsBrandRouteImport } from './routes/$locale/reparations.$brand'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as AuthenticatedAdminAnalyticsAdvancedRouteImport } from './routes/_authenticated/admin/analytics-advanced'
import { Route as AuthenticatedAdminAtelierRouteImport } from './routes/_authenticated/admin/atelier'
import { Route as AuthenticatedAdminAteliersRouteImport } from './routes/_authenticated/admin/ateliers'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as AuthenticatedAdminCaisseRouteImport } from './routes/_authenticated/admin/caisse'
import { Route as AuthenticatedAdminCatalogueRouteImport } from './routes/_authenticated/admin/catalogue'
import { Route as AuthenticatedAdminChatRouteImport } from './routes/_authenticated/admin/chat'
import { Route as AuthenticatedAdminCommandesRouteImport } from './routes/_authenticated/admin/commandes'
import { Route as AuthenticatedAdminContenuRouteImport } from './routes/_authenticated/admin/contenu'
import { Route as AuthenticatedAdminDossiersRouteImport } from './routes/_authenticated/admin/dossiers'
import { Route as AuthenticatedAdminEquipeRouteImport } from './routes/_authenticated/admin/equipe'
import { Route as AuthenticatedAdminFeatureFlagsRouteImport } from './routes/_authenticated/admin/feature-flags'
import { Route as AuthenticatedAdminFournisseursRouteImport } from './routes/_authenticated/admin/fournisseurs'
import { Route as AuthenticatedAdminInventaireRouteImport } from './routes/_authenticated/admin/inventaire'
import { Route as AuthenticatedAdminKbRouteImport } from './routes/_authenticated/admin/kb'
import { Route as AuthenticatedAdminKpisRouteImport } from './routes/_authenticated/admin/kpis'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin/leads'
import { Route as AuthenticatedAdminLivraisonsRouteImport } from './routes/_authenticated/admin/livraisons'
import { Route as AuthenticatedAdminMarketingRouteImport } from './routes/_authenticated/admin/marketing'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminParrainageRouteImport } from './routes/_authenticated/admin/parrainage'
import { Route as AuthenticatedAdminRapportsRouteImport } from './routes/_authenticated/admin/rapports'
import { Route as AuthenticatedAdminReclamationsRouteImport } from './routes/_authenticated/admin/reclamations'
import { Route as AuthenticatedAdminRemboursementsRouteImport } from './routes/_authenticated/admin/remboursements'
import { Route as AuthenticatedAdminRetoursRouteImport } from './routes/_authenticated/admin/retours'
import { Route as AuthenticatedAdminSatisfactionRouteImport } from './routes/_authenticated/admin/satisfaction'
import { Route as AuthenticatedAdminSecuriteRouteImport } from './routes/_authenticated/admin/securite'
import { Route as AuthenticatedAdminSlaRouteImport } from './routes/_authenticated/admin/sla'
import { Route as AuthenticatedAdminStatsRouteImport } from './routes/_authenticated/admin/stats'
import { Route as AuthenticatedAdminWebhooksRouteImport } from './routes/_authenticated/admin/webhooks'
import { Route as ApiV1SplatRouteImport } from './routes/api.v1.$'
import { Route as AppOrganizationsOrgIdRouteImport } from './routes/app.organizations.$orgId'
import { Route as AppOrganizationsOrgIdBillingRouteImport } from './routes/app.organizations.$orgId.billing'
import { Route as AppOrganizationsOrgIdEquipmentRouteImport } from './routes/app.organizations.$orgId.equipment'
import { Route as AppOrganizationsOrgIdMaintenanceRouteImport } from './routes/app.organizations.$orgId.maintenance'
import { Route as AppOrganizationsOrgIdSitesRouteImport } from './routes/app.organizations.$orgId.sites'
import { Route as AppOrganizationsOrgIdTicketsRouteImport } from './routes/app.organizations.$orgId.tickets'
import { Route as AppOrganizationsOrgIdEquipmentEquipmentIdRouteImport } from './routes/app.organizations.$orgId.equipment.$equipmentId'
import { Route as AppOrganizationsOrgIdTicketsTicketIdRouteImport } from './routes/app.organizations.$orgId.tickets.$ticketId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAvisRoute = LocaleAvisRouteImport.update({
  id: '/avis',
  path: '/avis',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCatalogueRoute = LocaleCatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleChangelogRoute = LocaleChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCheckoutRoute = LocaleCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleContactRoute = LocaleContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleDevisRoute = LocaleDevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleEngagementsRoute = LocaleEngagementsRouteImport.update({
  id: '/engagements',
  path: '/engagements',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleEntreprisesRoute = LocaleEntreprisesRouteImport.update({
  id: '/entreprises',
  path: '/entreprises',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleFaqRoute = LocaleFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleGarantieRoute = LocaleGarantieRouteImport.update({
  id: '/garantie',
  path: '/garantie',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleGuidesRoute = LocaleGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleHistoriqueRoute = LocaleHistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleMagasinsRoute = LocaleMagasinsRouteImport.update({
  id: '/magasins',
  path: '/magasins',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleMentionsLegalesRoute = LocaleMentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePanierRoute = LocalePanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePromotionsRoute = LocalePromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleReclamationRoute = LocaleReclamationRouteImport.update({
  id: '/reclamation',
  path: '/reclamation',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleReconditionnesRoute = LocaleReconditionnesRouteImport.update({
  id: '/reconditionnes',
  path: '/reconditionnes',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleRepriseRoute = LocaleRepriseRouteImport.update({
  id: '/reprise',
  path: '/reprise',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleReservationRoute = LocaleReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleServicesRoute = LocaleServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSuiviRoute = LocaleSuiviRouteImport.update({
  id: '/suivi',
  path: '/suivi',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleTarifsRoute = LocaleTarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleWorkAtRoute = LocaleWorkAtRouteImport.update({
  id: '/work-at',
  path: '/work-at',
  getParentRoute: () => LocaleRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonCompteRoute = AuthenticatedMonCompteRouteImport.update({
  id: '/mon-compte',
  path: '/mon-compte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewsAdminRoute =
  AuthenticatedReviewsAdminRouteImport.update({
    id: '/reviews-admin',
    path: '/reviews-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiCronRemindersRoute = ApiCronRemindersRouteImport.update({
  id: '/api/cron-reminders',
  path: '/api/cron-reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api/docs',
  path: '/api/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFedapayWebhookRoute = ApiFedapayWebhookRouteImport.update({
  id: '/api/fedapay-webhook',
  path: '/api/fedapay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFlutterwaveWebhookRoute = ApiFlutterwaveWebhookRouteImport.update({
  id: '/api/flutterwave-webhook',
  path: '/api/flutterwave-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthzRoute = ApiHealthzRouteImport.update({
  id: '/api/healthz',
  path: '/api/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIcalRoute = ApiIcalRouteImport.update({
  id: '/api/ical',
  path: '/api/ical',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKkiapayWebhookRoute = ApiKkiapayWebhookRouteImport.update({
  id: '/api/kkiapay-webhook',
  path: '/api/kkiapay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushSubscribeRoute = ApiPushSubscribeRouteImport.update({
  id: '/api/push-subscribe',
  path: '/api/push-subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupDashboardRoute = AppGroupDashboardRouteImport.update({
  id: '/group-dashboard',
  path: '/group-dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const LocaleAppareilSlugRoute = LocaleAppareilSlugRouteImport.update({
  id: '/appareil/$slug',
  path: '/appareil/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBlogIndexRoute = LocaleBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBlogSlugRoute = LocaleBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBoutiqueIndexRoute = LocaleBoutiqueIndexRouteImport.update({
  id: '/boutique/',
  path: '/boutique/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBoutiqueSlugRoute = LocaleBoutiqueSlugRouteImport.update({
  id: '/boutique/$slug',
  path: '/boutique/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBoutiqueComparerRoute = LocaleBoutiqueComparerRouteImport.update({
  id: '/boutique/comparer',
  path: '/boutique/comparer',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleQuartiersIndexRoute = LocaleQuartiersIndexRouteImport.update({
  id: '/quartiers/',
  path: '/quartiers/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleQuartiersSlugRoute = LocaleQuartiersSlugRouteImport.update({
  id: '/quartiers/$slug',
  path: '/quartiers/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleReparationsIndexRoute = LocaleReparationsIndexRouteImport.update({
  id: '/reparations/',
  path: '/reparations/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleReparationsBrandRoute = LocaleReparationsBrandRouteImport.update({
  id: '/reparations/$brand',
  path: '/reparations/$brand',
  getParentRoute: () => LocaleRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsAdvancedRoute =
  AuthenticatedAdminAnalyticsAdvancedRouteImport.update({
    id: '/analytics-advanced',
    path: '/analytics-advanced',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAtelierRoute =
  AuthenticatedAdminAtelierRouteImport.update({
    id: '/atelier',
    path: '/atelier',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAteliersRoute =
  AuthenticatedAdminAteliersRouteImport.update({
    id: '/ateliers',
    path: '/ateliers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCaisseRoute =
  AuthenticatedAdminCaisseRouteImport.update({
    id: '/caisse',
    path: '/caisse',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCatalogueRoute =
  AuthenticatedAdminCatalogueRouteImport.update({
    id: '/catalogue',
    path: '/catalogue',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminChatRoute = AuthenticatedAdminChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCommandesRoute =
  AuthenticatedAdminCommandesRouteImport.update({
    id: '/commandes',
    path: '/commandes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContenuRoute =
  AuthenticatedAdminContenuRouteImport.update({
    id: '/contenu',
    path: '/contenu',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDossiersRoute =
  AuthenticatedAdminDossiersRouteImport.update({
    id: '/dossiers',
    path: '/dossiers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEquipeRoute =
  AuthenticatedAdminEquipeRouteImport.update({
    id: '/equipe',
    path: '/equipe',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFeatureFlagsRoute =
  AuthenticatedAdminFeatureFlagsRouteImport.update({
    id: '/feature-flags',
    path: '/feature-flags',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFournisseursRoute =
  AuthenticatedAdminFournisseursRouteImport.update({
    id: '/fournisseurs',
    path: '/fournisseurs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInventaireRoute =
  AuthenticatedAdminInventaireRouteImport.update({
    id: '/inventaire',
    path: '/inventaire',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminKbRoute = AuthenticatedAdminKbRouteImport.update({
  id: '/kb',
  path: '/kb',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminKpisRoute = AuthenticatedAdminKpisRouteImport.update({
  id: '/kpis',
  path: '/kpis',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminLivraisonsRoute =
  AuthenticatedAdminLivraisonsRouteImport.update({
    id: '/livraisons',
    path: '/livraisons',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMarketingRoute =
  AuthenticatedAdminMarketingRouteImport.update({
    id: '/marketing',
    path: '/marketing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminParrainageRoute =
  AuthenticatedAdminParrainageRouteImport.update({
    id: '/parrainage',
    path: '/parrainage',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRapportsRoute =
  AuthenticatedAdminRapportsRouteImport.update({
    id: '/rapports',
    path: '/rapports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReclamationsRoute =
  AuthenticatedAdminReclamationsRouteImport.update({
    id: '/reclamations',
    path: '/reclamations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRemboursementsRoute =
  AuthenticatedAdminRemboursementsRouteImport.update({
    id: '/remboursements',
    path: '/remboursements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRetoursRoute =
  AuthenticatedAdminRetoursRouteImport.update({
    id: '/retours',
    path: '/retours',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSatisfactionRoute =
  AuthenticatedAdminSatisfactionRouteImport.update({
    id: '/satisfaction',
    path: '/satisfaction',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSecuriteRoute =
  AuthenticatedAdminSecuriteRouteImport.update({
    id: '/securite',
    path: '/securite',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSlaRoute = AuthenticatedAdminSlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminStatsRoute = AuthenticatedAdminStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminWebhooksRoute =
  AuthenticatedAdminWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrganizationsOrgIdRoute = AppOrganizationsOrgIdRouteImport.update({
  id: '/organizations/$orgId',
  path: '/organizations/$orgId',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsOrgIdBillingRoute =
  AppOrganizationsOrgIdBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AppOrganizationsOrgIdRoute,
  } as any)
const AppOrganizationsOrgIdEquipmentRoute =
  AppOrganizationsOrgIdEquipmentRouteImport.update({
    id: '/equipment',
    path: '/equipment',
    getParentRoute: () => AppOrganizationsOrgIdRoute,
  } as any)
const AppOrganizationsOrgIdMaintenanceRoute =
  AppOrganizationsOrgIdMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AppOrganizationsOrgIdRoute,
  } as any)
const AppOrganizationsOrgIdSitesRoute =
  AppOrganizationsOrgIdSitesRouteImport.update({
    id: '/sites',
    path: '/sites',
    getParentRoute: () => AppOrganizationsOrgIdRoute,
  } as any)
const AppOrganizationsOrgIdTicketsRoute =
  AppOrganizationsOrgIdTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AppOrganizationsOrgIdRoute,
  } as any)
const AppOrganizationsOrgIdEquipmentEquipmentIdRoute =
  AppOrganizationsOrgIdEquipmentEquipmentIdRouteImport.update({
    id: '/$equipmentId',
    path: '/$equipmentId',
    getParentRoute: () => AppOrganizationsOrgIdEquipmentRoute,
  } as any)
const AppOrganizationsOrgIdTicketsTicketIdRoute =
  AppOrganizationsOrgIdTicketsTicketIdRouteImport.update({
    id: '/$ticketId',
    path: '/$ticketId',
    getParentRoute: () => AppOrganizationsOrgIdTicketsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/avis': typeof LocaleAvisRoute
  '/$locale/catalogue': typeof LocaleCatalogueRoute
  '/$locale/changelog': typeof LocaleChangelogRoute
  '/$locale/checkout': typeof LocaleCheckoutRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/devis': typeof LocaleDevisRoute
  '/$locale/engagements': typeof LocaleEngagementsRoute
  '/$locale/entreprises': typeof LocaleEntreprisesRoute
  '/$locale/faq': typeof LocaleFaqRoute
  '/$locale/garantie': typeof LocaleGarantieRoute
  '/$locale/guides': typeof LocaleGuidesRoute
  '/$locale/historique': typeof LocaleHistoriqueRoute
  '/$locale/magasins': typeof LocaleMagasinsRoute
  '/$locale/mentions-legales': typeof LocaleMentionsLegalesRoute
  '/$locale/panier': typeof LocalePanierRoute
  '/$locale/promotions': typeof LocalePromotionsRoute
  '/$locale/reclamation': typeof LocaleReclamationRoute
  '/$locale/reconditionnes': typeof LocaleReconditionnesRoute
  '/$locale/reprise': typeof LocaleRepriseRoute
  '/$locale/reservation': typeof LocaleReservationRoute
  '/$locale/services': typeof LocaleServicesRoute
  '/$locale/suivi': typeof LocaleSuiviRoute
  '/$locale/tarifs': typeof LocaleTarifsRoute
  '/$locale/work-at': typeof LocaleWorkAtRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/mon-compte': typeof AuthenticatedMonCompteRoute
  '/reviews-admin': typeof AuthenticatedReviewsAdminRoute
  '/api/cron-reminders': typeof ApiCronRemindersRoute
  '/api/docs': typeof ApiDocsRoute
  '/api/fedapay-webhook': typeof ApiFedapayWebhookRoute
  '/api/flutterwave-webhook': typeof ApiFlutterwaveWebhookRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/api/ical': typeof ApiIcalRoute
  '/api/kkiapay-webhook': typeof ApiKkiapayWebhookRoute
  '/api/push-subscribe': typeof ApiPushSubscribeRoute
  '/app/group-dashboard': typeof AppGroupDashboardRoute
  '/app/scan': typeof AppScanRoute
  '/$locale/': typeof LocaleIndexRoute
  '/app/': typeof AppIndexRoute
  '/$locale/appareil/$slug': typeof LocaleAppareilSlugRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/boutique/$slug': typeof LocaleBoutiqueSlugRoute
  '/$locale/boutique/comparer': typeof LocaleBoutiqueComparerRoute
  '/$locale/quartiers/$slug': typeof LocaleQuartiersSlugRoute
  '/$locale/reparations/$brand': typeof LocaleReparationsBrandRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/analytics-advanced': typeof AuthenticatedAdminAnalyticsAdvancedRoute
  '/admin/atelier': typeof AuthenticatedAdminAtelierRoute
  '/admin/ateliers': typeof AuthenticatedAdminAteliersRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/caisse': typeof AuthenticatedAdminCaisseRoute
  '/admin/catalogue': typeof AuthenticatedAdminCatalogueRoute
  '/admin/chat': typeof AuthenticatedAdminChatRoute
  '/admin/commandes': typeof AuthenticatedAdminCommandesRoute
  '/admin/contenu': typeof AuthenticatedAdminContenuRoute
  '/admin/dossiers': typeof AuthenticatedAdminDossiersRoute
  '/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/admin/feature-flags': typeof AuthenticatedAdminFeatureFlagsRoute
  '/admin/fournisseurs': typeof AuthenticatedAdminFournisseursRoute
  '/admin/inventaire': typeof AuthenticatedAdminInventaireRoute
  '/admin/kb': typeof AuthenticatedAdminKbRoute
  '/admin/kpis': typeof AuthenticatedAdminKpisRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/livraisons': typeof AuthenticatedAdminLivraisonsRoute
  '/admin/marketing': typeof AuthenticatedAdminMarketingRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/parrainage': typeof AuthenticatedAdminParrainageRoute
  '/admin/rapports': typeof AuthenticatedAdminRapportsRoute
  '/admin/reclamations': typeof AuthenticatedAdminReclamationsRoute
  '/admin/remboursements': typeof AuthenticatedAdminRemboursementsRoute
  '/admin/retours': typeof AuthenticatedAdminRetoursRoute
  '/admin/satisfaction': typeof AuthenticatedAdminSatisfactionRoute
  '/admin/securite': typeof AuthenticatedAdminSecuriteRoute
  '/admin/sla': typeof AuthenticatedAdminSlaRoute
  '/admin/stats': typeof AuthenticatedAdminStatsRoute
  '/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/app/organizations/$orgId': typeof AppOrganizationsOrgIdRouteWithChildren
  '/$locale/blog/': typeof LocaleBlogIndexRoute
  '/$locale/boutique/': typeof LocaleBoutiqueIndexRoute
  '/$locale/quartiers/': typeof LocaleQuartiersIndexRoute
  '/$locale/reparations/': typeof LocaleReparationsIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/organizations/$orgId/billing': typeof AppOrganizationsOrgIdBillingRoute
  '/app/organizations/$orgId/equipment': typeof AppOrganizationsOrgIdEquipmentRouteWithChildren
  '/app/organizations/$orgId/maintenance': typeof AppOrganizationsOrgIdMaintenanceRoute
  '/app/organizations/$orgId/sites': typeof AppOrganizationsOrgIdSitesRoute
  '/app/organizations/$orgId/tickets': typeof AppOrganizationsOrgIdTicketsRouteWithChildren
  '/app/organizations/$orgId/equipment/$equipmentId': typeof AppOrganizationsOrgIdEquipmentEquipmentIdRoute
  '/app/organizations/$orgId/tickets/$ticketId': typeof AppOrganizationsOrgIdTicketsTicketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/avis': typeof LocaleAvisRoute
  '/$locale/catalogue': typeof LocaleCatalogueRoute
  '/$locale/changelog': typeof LocaleChangelogRoute
  '/$locale/checkout': typeof LocaleCheckoutRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/devis': typeof LocaleDevisRoute
  '/$locale/engagements': typeof LocaleEngagementsRoute
  '/$locale/entreprises': typeof LocaleEntreprisesRoute
  '/$locale/faq': typeof LocaleFaqRoute
  '/$locale/garantie': typeof LocaleGarantieRoute
  '/$locale/guides': typeof LocaleGuidesRoute
  '/$locale/historique': typeof LocaleHistoriqueRoute
  '/$locale/magasins': typeof LocaleMagasinsRoute
  '/$locale/mentions-legales': typeof LocaleMentionsLegalesRoute
  '/$locale/panier': typeof LocalePanierRoute
  '/$locale/promotions': typeof LocalePromotionsRoute
  '/$locale/reclamation': typeof LocaleReclamationRoute
  '/$locale/reconditionnes': typeof LocaleReconditionnesRoute
  '/$locale/reprise': typeof LocaleRepriseRoute
  '/$locale/reservation': typeof LocaleReservationRoute
  '/$locale/services': typeof LocaleServicesRoute
  '/$locale/suivi': typeof LocaleSuiviRoute
  '/$locale/tarifs': typeof LocaleTarifsRoute
  '/$locale/work-at': typeof LocaleWorkAtRoute
  '/mon-compte': typeof AuthenticatedMonCompteRoute
  '/reviews-admin': typeof AuthenticatedReviewsAdminRoute
  '/api/cron-reminders': typeof ApiCronRemindersRoute
  '/api/docs': typeof ApiDocsRoute
  '/api/fedapay-webhook': typeof ApiFedapayWebhookRoute
  '/api/flutterwave-webhook': typeof ApiFlutterwaveWebhookRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/api/ical': typeof ApiIcalRoute
  '/api/kkiapay-webhook': typeof ApiKkiapayWebhookRoute
  '/api/push-subscribe': typeof ApiPushSubscribeRoute
  '/app/group-dashboard': typeof AppGroupDashboardRoute
  '/app/scan': typeof AppScanRoute
  '/$locale': typeof LocaleIndexRoute
  '/app': typeof AppIndexRoute
  '/$locale/appareil/$slug': typeof LocaleAppareilSlugRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/boutique/$slug': typeof LocaleBoutiqueSlugRoute
  '/$locale/boutique/comparer': typeof LocaleBoutiqueComparerRoute
  '/$locale/quartiers/$slug': typeof LocaleQuartiersSlugRoute
  '/$locale/reparations/$brand': typeof LocaleReparationsBrandRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/analytics-advanced': typeof AuthenticatedAdminAnalyticsAdvancedRoute
  '/admin/atelier': typeof AuthenticatedAdminAtelierRoute
  '/admin/ateliers': typeof AuthenticatedAdminAteliersRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/caisse': typeof AuthenticatedAdminCaisseRoute
  '/admin/catalogue': typeof AuthenticatedAdminCatalogueRoute
  '/admin/chat': typeof AuthenticatedAdminChatRoute
  '/admin/commandes': typeof AuthenticatedAdminCommandesRoute
  '/admin/contenu': typeof AuthenticatedAdminContenuRoute
  '/admin/dossiers': typeof AuthenticatedAdminDossiersRoute
  '/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/admin/feature-flags': typeof AuthenticatedAdminFeatureFlagsRoute
  '/admin/fournisseurs': typeof AuthenticatedAdminFournisseursRoute
  '/admin/inventaire': typeof AuthenticatedAdminInventaireRoute
  '/admin/kb': typeof AuthenticatedAdminKbRoute
  '/admin/kpis': typeof AuthenticatedAdminKpisRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/livraisons': typeof AuthenticatedAdminLivraisonsRoute
  '/admin/marketing': typeof AuthenticatedAdminMarketingRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/parrainage': typeof AuthenticatedAdminParrainageRoute
  '/admin/rapports': typeof AuthenticatedAdminRapportsRoute
  '/admin/reclamations': typeof AuthenticatedAdminReclamationsRoute
  '/admin/remboursements': typeof AuthenticatedAdminRemboursementsRoute
  '/admin/retours': typeof AuthenticatedAdminRetoursRoute
  '/admin/satisfaction': typeof AuthenticatedAdminSatisfactionRoute
  '/admin/securite': typeof AuthenticatedAdminSecuriteRoute
  '/admin/sla': typeof AuthenticatedAdminSlaRoute
  '/admin/stats': typeof AuthenticatedAdminStatsRoute
  '/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/app/organizations/$orgId': typeof AppOrganizationsOrgIdRouteWithChildren
  '/$locale/blog': typeof LocaleBlogIndexRoute
  '/$locale/boutique': typeof LocaleBoutiqueIndexRoute
  '/$locale/quartiers': typeof LocaleQuartiersIndexRoute
  '/$locale/reparations': typeof LocaleReparationsIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app/organizations/$orgId/billing': typeof AppOrganizationsOrgIdBillingRoute
  '/app/organizations/$orgId/equipment': typeof AppOrganizationsOrgIdEquipmentRouteWithChildren
  '/app/organizations/$orgId/maintenance': typeof AppOrganizationsOrgIdMaintenanceRoute
  '/app/organizations/$orgId/sites': typeof AppOrganizationsOrgIdSitesRoute
  '/app/organizations/$orgId/tickets': typeof AppOrganizationsOrgIdTicketsRouteWithChildren
  '/app/organizations/$orgId/equipment/$equipmentId': typeof AppOrganizationsOrgIdEquipmentEquipmentIdRoute
  '/app/organizations/$orgId/tickets/$ticketId': typeof AppOrganizationsOrgIdTicketsTicketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$locale': typeof LocaleRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/avis': typeof LocaleAvisRoute
  '/$locale/catalogue': typeof LocaleCatalogueRoute
  '/$locale/changelog': typeof LocaleChangelogRoute
  '/$locale/checkout': typeof LocaleCheckoutRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/devis': typeof LocaleDevisRoute
  '/$locale/engagements': typeof LocaleEngagementsRoute
  '/$locale/entreprises': typeof LocaleEntreprisesRoute
  '/$locale/faq': typeof LocaleFaqRoute
  '/$locale/garantie': typeof LocaleGarantieRoute
  '/$locale/guides': typeof LocaleGuidesRoute
  '/$locale/historique': typeof LocaleHistoriqueRoute
  '/$locale/magasins': typeof LocaleMagasinsRoute
  '/$locale/mentions-legales': typeof LocaleMentionsLegalesRoute
  '/$locale/panier': typeof LocalePanierRoute
  '/$locale/promotions': typeof LocalePromotionsRoute
  '/$locale/reclamation': typeof LocaleReclamationRoute
  '/$locale/reconditionnes': typeof LocaleReconditionnesRoute
  '/$locale/reprise': typeof LocaleRepriseRoute
  '/$locale/reservation': typeof LocaleReservationRoute
  '/$locale/services': typeof LocaleServicesRoute
  '/$locale/suivi': typeof LocaleSuiviRoute
  '/$locale/tarifs': typeof LocaleTarifsRoute
  '/$locale/work-at': typeof LocaleWorkAtRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/mon-compte': typeof AuthenticatedMonCompteRoute
  '/_authenticated/reviews-admin': typeof AuthenticatedReviewsAdminRoute
  '/api/cron-reminders': typeof ApiCronRemindersRoute
  '/api/docs': typeof ApiDocsRoute
  '/api/fedapay-webhook': typeof ApiFedapayWebhookRoute
  '/api/flutterwave-webhook': typeof ApiFlutterwaveWebhookRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/api/ical': typeof ApiIcalRoute
  '/api/kkiapay-webhook': typeof ApiKkiapayWebhookRoute
  '/api/push-subscribe': typeof ApiPushSubscribeRoute
  '/app/group-dashboard': typeof AppGroupDashboardRoute
  '/app/scan': typeof AppScanRoute
  '/$locale/': typeof LocaleIndexRoute
  '/app/': typeof AppIndexRoute
  '/$locale/appareil/$slug': typeof LocaleAppareilSlugRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/boutique/$slug': typeof LocaleBoutiqueSlugRoute
  '/$locale/boutique/comparer': typeof LocaleBoutiqueComparerRoute
  '/$locale/quartiers/$slug': typeof LocaleQuartiersSlugRoute
  '/$locale/reparations/$brand': typeof LocaleReparationsBrandRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/analytics-advanced': typeof AuthenticatedAdminAnalyticsAdvancedRoute
  '/_authenticated/admin/atelier': typeof AuthenticatedAdminAtelierRoute
  '/_authenticated/admin/ateliers': typeof AuthenticatedAdminAteliersRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/caisse': typeof AuthenticatedAdminCaisseRoute
  '/_authenticated/admin/catalogue': typeof AuthenticatedAdminCatalogueRoute
  '/_authenticated/admin/chat': typeof AuthenticatedAdminChatRoute
  '/_authenticated/admin/commandes': typeof AuthenticatedAdminCommandesRoute
  '/_authenticated/admin/contenu': typeof AuthenticatedAdminContenuRoute
  '/_authenticated/admin/dossiers': typeof AuthenticatedAdminDossiersRoute
  '/_authenticated/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/_authenticated/admin/feature-flags': typeof AuthenticatedAdminFeatureFlagsRoute
  '/_authenticated/admin/fournisseurs': typeof AuthenticatedAdminFournisseursRoute
  '/_authenticated/admin/inventaire': typeof AuthenticatedAdminInventaireRoute
  '/_authenticated/admin/kb': typeof AuthenticatedAdminKbRoute
  '/_authenticated/admin/kpis': typeof AuthenticatedAdminKpisRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/livraisons': typeof AuthenticatedAdminLivraisonsRoute
  '/_authenticated/admin/marketing': typeof AuthenticatedAdminMarketingRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/parrainage': typeof AuthenticatedAdminParrainageRoute
  '/_authenticated/admin/rapports': typeof AuthenticatedAdminRapportsRoute
  '/_authenticated/admin/reclamations': typeof AuthenticatedAdminReclamationsRoute
  '/_authenticated/admin/remboursements': typeof AuthenticatedAdminRemboursementsRoute
  '/_authenticated/admin/retours': typeof AuthenticatedAdminRetoursRoute
  '/_authenticated/admin/satisfaction': typeof AuthenticatedAdminSatisfactionRoute
  '/_authenticated/admin/securite': typeof AuthenticatedAdminSecuriteRoute
  '/_authenticated/admin/sla': typeof AuthenticatedAdminSlaRoute
  '/_authenticated/admin/stats': typeof AuthenticatedAdminStatsRoute
  '/_authenticated/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/app/organizations/$orgId': typeof AppOrganizationsOrgIdRouteWithChildren
  '/$locale/blog/': typeof LocaleBlogIndexRoute
  '/$locale/boutique/': typeof LocaleBoutiqueIndexRoute
  '/$locale/quartiers/': typeof LocaleQuartiersIndexRoute
  '/$locale/reparations/': typeof LocaleReparationsIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/organizations/$orgId/billing': typeof AppOrganizationsOrgIdBillingRoute
  '/app/organizations/$orgId/equipment': typeof AppOrganizationsOrgIdEquipmentRouteWithChildren
  '/app/organizations/$orgId/maintenance': typeof AppOrganizationsOrgIdMaintenanceRoute
  '/app/organizations/$orgId/sites': typeof AppOrganizationsOrgIdSitesRoute
  '/app/organizations/$orgId/tickets': typeof AppOrganizationsOrgIdTicketsRouteWithChildren
  '/app/organizations/$orgId/equipment/$equipmentId': typeof AppOrganizationsOrgIdEquipmentEquipmentIdRoute
  '/app/organizations/$orgId/tickets/$ticketId': typeof AppOrganizationsOrgIdTicketsTicketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/app'
    | '/auth'
    | '/demo'
    | '/sitemap.xml'
    | '/$locale/about'
    | '/$locale/avis'
    | '/$locale/catalogue'
    | '/$locale/changelog'
    | '/$locale/checkout'
    | '/$locale/contact'
    | '/$locale/devis'
    | '/$locale/engagements'
    | '/$locale/entreprises'
    | '/$locale/faq'
    | '/$locale/garantie'
    | '/$locale/guides'
    | '/$locale/historique'
    | '/$locale/magasins'
    | '/$locale/mentions-legales'
    | '/$locale/panier'
    | '/$locale/promotions'
    | '/$locale/reclamation'
    | '/$locale/reconditionnes'
    | '/$locale/reprise'
    | '/$locale/reservation'
    | '/$locale/services'
    | '/$locale/suivi'
    | '/$locale/tarifs'
    | '/$locale/work-at'
    | '/admin'
    | '/mon-compte'
    | '/reviews-admin'
    | '/api/cron-reminders'
    | '/api/docs'
    | '/api/fedapay-webhook'
    | '/api/flutterwave-webhook'
    | '/api/healthz'
    | '/api/ical'
    | '/api/kkiapay-webhook'
    | '/api/push-subscribe'
    | '/app/group-dashboard'
    | '/app/scan'
    | '/$locale/'
    | '/app/'
    | '/$locale/appareil/$slug'
    | '/$locale/blog/$slug'
    | '/$locale/boutique/$slug'
    | '/$locale/boutique/comparer'
    | '/$locale/quartiers/$slug'
    | '/$locale/reparations/$brand'
    | '/admin/analytics'
    | '/admin/analytics-advanced'
    | '/admin/atelier'
    | '/admin/ateliers'
    | '/admin/audit'
    | '/admin/caisse'
    | '/admin/catalogue'
    | '/admin/chat'
    | '/admin/commandes'
    | '/admin/contenu'
    | '/admin/dossiers'
    | '/admin/equipe'
    | '/admin/feature-flags'
    | '/admin/fournisseurs'
    | '/admin/inventaire'
    | '/admin/kb'
    | '/admin/kpis'
    | '/admin/leads'
    | '/admin/livraisons'
    | '/admin/marketing'
    | '/admin/notifications'
    | '/admin/parrainage'
    | '/admin/rapports'
    | '/admin/reclamations'
    | '/admin/remboursements'
    | '/admin/retours'
    | '/admin/satisfaction'
    | '/admin/securite'
    | '/admin/sla'
    | '/admin/stats'
    | '/admin/webhooks'
    | '/api/v1/$'
    | '/app/organizations/$orgId'
    | '/$locale/blog/'
    | '/$locale/boutique/'
    | '/$locale/quartiers/'
    | '/$locale/reparations/'
    | '/admin/'
    | '/app/organizations/$orgId/billing'
    | '/app/organizations/$orgId/equipment'
    | '/app/organizations/$orgId/maintenance'
    | '/app/organizations/$orgId/sites'
    | '/app/organizations/$orgId/tickets'
    | '/app/organizations/$orgId/equipment/$equipmentId'
    | '/app/organizations/$orgId/tickets/$ticketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/demo'
    | '/sitemap.xml'
    | '/$locale/about'
    | '/$locale/avis'
    | '/$locale/catalogue'
    | '/$locale/changelog'
    | '/$locale/checkout'
    | '/$locale/contact'
    | '/$locale/devis'
    | '/$locale/engagements'
    | '/$locale/entreprises'
    | '/$locale/faq'
    | '/$locale/garantie'
    | '/$locale/guides'
    | '/$locale/historique'
    | '/$locale/magasins'
    | '/$locale/mentions-legales'
    | '/$locale/panier'
    | '/$locale/promotions'
    | '/$locale/reclamation'
    | '/$locale/reconditionnes'
    | '/$locale/reprise'
    | '/$locale/reservation'
    | '/$locale/services'
    | '/$locale/suivi'
    | '/$locale/tarifs'
    | '/$locale/work-at'
    | '/mon-compte'
    | '/reviews-admin'
    | '/api/cron-reminders'
    | '/api/docs'
    | '/api/fedapay-webhook'
    | '/api/flutterwave-webhook'
    | '/api/healthz'
    | '/api/ical'
    | '/api/kkiapay-webhook'
    | '/api/push-subscribe'
    | '/app/group-dashboard'
    | '/app/scan'
    | '/$locale'
    | '/app'
    | '/$locale/appareil/$slug'
    | '/$locale/blog/$slug'
    | '/$locale/boutique/$slug'
    | '/$locale/boutique/comparer'
    | '/$locale/quartiers/$slug'
    | '/$locale/reparations/$brand'
    | '/admin/analytics'
    | '/admin/analytics-advanced'
    | '/admin/atelier'
    | '/admin/ateliers'
    | '/admin/audit'
    | '/admin/caisse'
    | '/admin/catalogue'
    | '/admin/chat'
    | '/admin/commandes'
    | '/admin/contenu'
    | '/admin/dossiers'
    | '/admin/equipe'
    | '/admin/feature-flags'
    | '/admin/fournisseurs'
    | '/admin/inventaire'
    | '/admin/kb'
    | '/admin/kpis'
    | '/admin/leads'
    | '/admin/livraisons'
    | '/admin/marketing'
    | '/admin/notifications'
    | '/admin/parrainage'
    | '/admin/rapports'
    | '/admin/reclamations'
    | '/admin/remboursements'
    | '/admin/retours'
    | '/admin/satisfaction'
    | '/admin/securite'
    | '/admin/sla'
    | '/admin/stats'
    | '/admin/webhooks'
    | '/api/v1/$'
    | '/app/organizations/$orgId'
    | '/$locale/blog'
    | '/$locale/boutique'
    | '/$locale/quartiers'
    | '/$locale/reparations'
    | '/admin'
    | '/app/organizations/$orgId/billing'
    | '/app/organizations/$orgId/equipment'
    | '/app/organizations/$orgId/maintenance'
    | '/app/organizations/$orgId/sites'
    | '/app/organizations/$orgId/tickets'
    | '/app/organizations/$orgId/equipment/$equipmentId'
    | '/app/organizations/$orgId/tickets/$ticketId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$locale'
    | '/app'
    | '/auth'
    | '/demo'
    | '/sitemap.xml'
    | '/$locale/about'
    | '/$locale/avis'
    | '/$locale/catalogue'
    | '/$locale/changelog'
    | '/$locale/checkout'
    | '/$locale/contact'
    | '/$locale/devis'
    | '/$locale/engagements'
    | '/$locale/entreprises'
    | '/$locale/faq'
    | '/$locale/garantie'
    | '/$locale/guides'
    | '/$locale/historique'
    | '/$locale/magasins'
    | '/$locale/mentions-legales'
    | '/$locale/panier'
    | '/$locale/promotions'
    | '/$locale/reclamation'
    | '/$locale/reconditionnes'
    | '/$locale/reprise'
    | '/$locale/reservation'
    | '/$locale/services'
    | '/$locale/suivi'
    | '/$locale/tarifs'
    | '/$locale/work-at'
    | '/_authenticated/admin'
    | '/_authenticated/mon-compte'
    | '/_authenticated/reviews-admin'
    | '/api/cron-reminders'
    | '/api/docs'
    | '/api/fedapay-webhook'
    | '/api/flutterwave-webhook'
    | '/api/healthz'
    | '/api/ical'
    | '/api/kkiapay-webhook'
    | '/api/push-subscribe'
    | '/app/group-dashboard'
    | '/app/scan'
    | '/$locale/'
    | '/app/'
    | '/$locale/appareil/$slug'
    | '/$locale/blog/$slug'
    | '/$locale/boutique/$slug'
    | '/$locale/boutique/comparer'
    | '/$locale/quartiers/$slug'
    | '/$locale/reparations/$brand'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/analytics-advanced'
    | '/_authenticated/admin/atelier'
    | '/_authenticated/admin/ateliers'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/caisse'
    | '/_authenticated/admin/catalogue'
    | '/_authenticated/admin/chat'
    | '/_authenticated/admin/commandes'
    | '/_authenticated/admin/contenu'
    | '/_authenticated/admin/dossiers'
    | '/_authenticated/admin/equipe'
    | '/_authenticated/admin/feature-flags'
    | '/_authenticated/admin/fournisseurs'
    | '/_authenticated/admin/inventaire'
    | '/_authenticated/admin/kb'
    | '/_authenticated/admin/kpis'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/livraisons'
    | '/_authenticated/admin/marketing'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/parrainage'
    | '/_authenticated/admin/rapports'
    | '/_authenticated/admin/reclamations'
    | '/_authenticated/admin/remboursements'
    | '/_authenticated/admin/retours'
    | '/_authenticated/admin/satisfaction'
    | '/_authenticated/admin/securite'
    | '/_authenticated/admin/sla'
    | '/_authenticated/admin/stats'
    | '/_authenticated/admin/webhooks'
    | '/api/v1/$'
    | '/app/organizations/$orgId'
    | '/$locale/blog/'
    | '/$locale/boutique/'
    | '/$locale/quartiers/'
    | '/$locale/reparations/'
    | '/_authenticated/admin/'
    | '/app/organizations/$orgId/billing'
    | '/app/organizations/$orgId/equipment'
    | '/app/organizations/$orgId/maintenance'
    | '/app/organizations/$orgId/sites'
    | '/app/organizations/$orgId/tickets'
    | '/app/organizations/$orgId/equipment/$equipmentId'
    | '/app/organizations/$orgId/tickets/$ticketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LocaleRoute: typeof LocaleRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  DemoRoute: typeof DemoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiCronRemindersRoute: typeof ApiCronRemindersRoute
  ApiDocsRoute: typeof ApiDocsRoute
  ApiFedapayWebhookRoute: typeof ApiFedapayWebhookRoute
  ApiFlutterwaveWebhookRoute: typeof ApiFlutterwaveWebhookRoute
  ApiHealthzRoute: typeof ApiHealthzRoute
  ApiIcalRoute: typeof ApiIcalRoute
  ApiKkiapayWebhookRoute: typeof ApiKkiapayWebhookRoute
  ApiPushSubscribeRoute: typeof ApiPushSubscribeRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/avis': {
      id: '/$locale/avis'
      path: '/avis'
      fullPath: '/$locale/avis'
      preLoaderRoute: typeof LocaleAvisRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/catalogue': {
      id: '/$locale/catalogue'
      path: '/catalogue'
      fullPath: '/$locale/catalogue'
      preLoaderRoute: typeof LocaleCatalogueRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/changelog': {
      id: '/$locale/changelog'
      path: '/changelog'
      fullPath: '/$locale/changelog'
      preLoaderRoute: typeof LocaleChangelogRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/checkout': {
      id: '/$locale/checkout'
      path: '/checkout'
      fullPath: '/$locale/checkout'
      preLoaderRoute: typeof LocaleCheckoutRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/contact': {
      id: '/$locale/contact'
      path: '/contact'
      fullPath: '/$locale/contact'
      preLoaderRoute: typeof LocaleContactRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/devis': {
      id: '/$locale/devis'
      path: '/devis'
      fullPath: '/$locale/devis'
      preLoaderRoute: typeof LocaleDevisRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/engagements': {
      id: '/$locale/engagements'
      path: '/engagements'
      fullPath: '/$locale/engagements'
      preLoaderRoute: typeof LocaleEngagementsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/entreprises': {
      id: '/$locale/entreprises'
      path: '/entreprises'
      fullPath: '/$locale/entreprises'
      preLoaderRoute: typeof LocaleEntreprisesRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/faq': {
      id: '/$locale/faq'
      path: '/faq'
      fullPath: '/$locale/faq'
      preLoaderRoute: typeof LocaleFaqRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/garantie': {
      id: '/$locale/garantie'
      path: '/garantie'
      fullPath: '/$locale/garantie'
      preLoaderRoute: typeof LocaleGarantieRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/guides': {
      id: '/$locale/guides'
      path: '/guides'
      fullPath: '/$locale/guides'
      preLoaderRoute: typeof LocaleGuidesRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/historique': {
      id: '/$locale/historique'
      path: '/historique'
      fullPath: '/$locale/historique'
      preLoaderRoute: typeof LocaleHistoriqueRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/magasins': {
      id: '/$locale/magasins'
      path: '/magasins'
      fullPath: '/$locale/magasins'
      preLoaderRoute: typeof LocaleMagasinsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/mentions-legales': {
      id: '/$locale/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/$locale/mentions-legales'
      preLoaderRoute: typeof LocaleMentionsLegalesRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/panier': {
      id: '/$locale/panier'
      path: '/panier'
      fullPath: '/$locale/panier'
      preLoaderRoute: typeof LocalePanierRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/promotions': {
      id: '/$locale/promotions'
      path: '/promotions'
      fullPath: '/$locale/promotions'
      preLoaderRoute: typeof LocalePromotionsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/reclamation': {
      id: '/$locale/reclamation'
      path: '/reclamation'
      fullPath: '/$locale/reclamation'
      preLoaderRoute: typeof LocaleReclamationRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/reconditionnes': {
      id: '/$locale/reconditionnes'
      path: '/reconditionnes'
      fullPath: '/$locale/reconditionnes'
      preLoaderRoute: typeof LocaleReconditionnesRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/reprise': {
      id: '/$locale/reprise'
      path: '/reprise'
      fullPath: '/$locale/reprise'
      preLoaderRoute: typeof LocaleRepriseRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/reservation': {
      id: '/$locale/reservation'
      path: '/reservation'
      fullPath: '/$locale/reservation'
      preLoaderRoute: typeof LocaleReservationRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/services': {
      id: '/$locale/services'
      path: '/services'
      fullPath: '/$locale/services'
      preLoaderRoute: typeof LocaleServicesRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/suivi': {
      id: '/$locale/suivi'
      path: '/suivi'
      fullPath: '/$locale/suivi'
      preLoaderRoute: typeof LocaleSuiviRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/tarifs': {
      id: '/$locale/tarifs'
      path: '/tarifs'
      fullPath: '/$locale/tarifs'
      preLoaderRoute: typeof LocaleTarifsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/work-at': {
      id: '/$locale/work-at'
      path: '/work-at'
      fullPath: '/$locale/work-at'
      preLoaderRoute: typeof LocaleWorkAtRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon-compte': {
      id: '/_authenticated/mon-compte'
      path: '/mon-compte'
      fullPath: '/mon-compte'
      preLoaderRoute: typeof AuthenticatedMonCompteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reviews-admin': {
      id: '/_authenticated/reviews-admin'
      path: '/reviews-admin'
      fullPath: '/reviews-admin'
      preLoaderRoute: typeof AuthenticatedReviewsAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/cron-reminders': {
      id: '/api/cron-reminders'
      path: '/api/cron-reminders'
      fullPath: '/api/cron-reminders'
      preLoaderRoute: typeof ApiCronRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docs': {
      id: '/api/docs'
      path: '/api/docs'
      fullPath: '/api/docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fedapay-webhook': {
      id: '/api/fedapay-webhook'
      path: '/api/fedapay-webhook'
      fullPath: '/api/fedapay-webhook'
      preLoaderRoute: typeof ApiFedapayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/flutterwave-webhook': {
      id: '/api/flutterwave-webhook'
      path: '/api/flutterwave-webhook'
      fullPath: '/api/flutterwave-webhook'
      preLoaderRoute: typeof ApiFlutterwaveWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/healthz': {
      id: '/api/healthz'
      path: '/api/healthz'
      fullPath: '/api/healthz'
      preLoaderRoute: typeof ApiHealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ical': {
      id: '/api/ical'
      path: '/api/ical'
      fullPath: '/api/ical'
      preLoaderRoute: typeof ApiIcalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kkiapay-webhook': {
      id: '/api/kkiapay-webhook'
      path: '/api/kkiapay-webhook'
      fullPath: '/api/kkiapay-webhook'
      preLoaderRoute: typeof ApiKkiapayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push-subscribe': {
      id: '/api/push-subscribe'
      path: '/api/push-subscribe'
      fullPath: '/api/push-subscribe'
      preLoaderRoute: typeof ApiPushSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/group-dashboard': {
      id: '/app/group-dashboard'
      path: '/group-dashboard'
      fullPath: '/app/group-dashboard'
      preLoaderRoute: typeof AppGroupDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scan': {
      id: '/app/scan'
      path: '/scan'
      fullPath: '/app/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/$locale/appareil/$slug': {
      id: '/$locale/appareil/$slug'
      path: '/appareil/$slug'
      fullPath: '/$locale/appareil/$slug'
      preLoaderRoute: typeof LocaleAppareilSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/blog/': {
      id: '/$locale/blog/'
      path: '/blog'
      fullPath: '/$locale/blog/'
      preLoaderRoute: typeof LocaleBlogIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/blog/$slug': {
      id: '/$locale/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/$locale/blog/$slug'
      preLoaderRoute: typeof LocaleBlogSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/boutique/': {
      id: '/$locale/boutique/'
      path: '/boutique'
      fullPath: '/$locale/boutique/'
      preLoaderRoute: typeof LocaleBoutiqueIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/boutique/$slug': {
      id: '/$locale/boutique/$slug'
      path: '/boutique/$slug'
      fullPath: '/$locale/boutique/$slug'
      preLoaderRoute: typeof LocaleBoutiqueSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/boutique/comparer': {
      id: '/$locale/boutique/comparer'
      path: '/boutique/comparer'
      fullPath: '/$locale/boutique/comparer'
      preLoaderRoute: typeof LocaleBoutiqueComparerRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/quartiers/': {
      id: '/$locale/quartiers/'
      path: '/quartiers'
      fullPath: '/$locale/quartiers/'
      preLoaderRoute: typeof LocaleQuartiersIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/quartiers/$slug': {
      id: '/$locale/quartiers/$slug'
      path: '/quartiers/$slug'
      fullPath: '/$locale/quartiers/$slug'
      preLoaderRoute: typeof LocaleQuartiersSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/reparations/': {
      id: '/$locale/reparations/'
      path: '/reparations'
      fullPath: '/$locale/reparations/'
      preLoaderRoute: typeof LocaleReparationsIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/reparations/$brand': {
      id: '/$locale/reparations/$brand'
      path: '/reparations/$brand'
      fullPath: '/$locale/reparations/$brand'
      preLoaderRoute: typeof LocaleReparationsBrandRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics-advanced': {
      id: '/_authenticated/admin/analytics-advanced'
      path: '/analytics-advanced'
      fullPath: '/admin/analytics-advanced'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsAdvancedRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/atelier': {
      id: '/_authenticated/admin/atelier'
      path: '/atelier'
      fullPath: '/admin/atelier'
      preLoaderRoute: typeof AuthenticatedAdminAtelierRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ateliers': {
      id: '/_authenticated/admin/ateliers'
      path: '/ateliers'
      fullPath: '/admin/ateliers'
      preLoaderRoute: typeof AuthenticatedAdminAteliersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/caisse': {
      id: '/_authenticated/admin/caisse'
      path: '/caisse'
      fullPath: '/admin/caisse'
      preLoaderRoute: typeof AuthenticatedAdminCaisseRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/catalogue': {
      id: '/_authenticated/admin/catalogue'
      path: '/catalogue'
      fullPath: '/admin/catalogue'
      preLoaderRoute: typeof AuthenticatedAdminCatalogueRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/chat': {
      id: '/_authenticated/admin/chat'
      path: '/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AuthenticatedAdminChatRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/commandes': {
      id: '/_authenticated/admin/commandes'
      path: '/commandes'
      fullPath: '/admin/commandes'
      preLoaderRoute: typeof AuthenticatedAdminCommandesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/contenu': {
      id: '/_authenticated/admin/contenu'
      path: '/contenu'
      fullPath: '/admin/contenu'
      preLoaderRoute: typeof AuthenticatedAdminContenuRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dossiers': {
      id: '/_authenticated/admin/dossiers'
      path: '/dossiers'
      fullPath: '/admin/dossiers'
      preLoaderRoute: typeof AuthenticatedAdminDossiersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/equipe': {
      id: '/_authenticated/admin/equipe'
      path: '/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof AuthenticatedAdminEquipeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/feature-flags': {
      id: '/_authenticated/admin/feature-flags'
      path: '/feature-flags'
      fullPath: '/admin/feature-flags'
      preLoaderRoute: typeof AuthenticatedAdminFeatureFlagsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/fournisseurs': {
      id: '/_authenticated/admin/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/admin/fournisseurs'
      preLoaderRoute: typeof AuthenticatedAdminFournisseursRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/inventaire': {
      id: '/_authenticated/admin/inventaire'
      path: '/inventaire'
      fullPath: '/admin/inventaire'
      preLoaderRoute: typeof AuthenticatedAdminInventaireRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/kb': {
      id: '/_authenticated/admin/kb'
      path: '/kb'
      fullPath: '/admin/kb'
      preLoaderRoute: typeof AuthenticatedAdminKbRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/kpis': {
      id: '/_authenticated/admin/kpis'
      path: '/kpis'
      fullPath: '/admin/kpis'
      preLoaderRoute: typeof AuthenticatedAdminKpisRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/livraisons': {
      id: '/_authenticated/admin/livraisons'
      path: '/livraisons'
      fullPath: '/admin/livraisons'
      preLoaderRoute: typeof AuthenticatedAdminLivraisonsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/marketing': {
      id: '/_authenticated/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AuthenticatedAdminMarketingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/parrainage': {
      id: '/_authenticated/admin/parrainage'
      path: '/parrainage'
      fullPath: '/admin/parrainage'
      preLoaderRoute: typeof AuthenticatedAdminParrainageRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/rapports': {
      id: '/_authenticated/admin/rapports'
      path: '/rapports'
      fullPath: '/admin/rapports'
      preLoaderRoute: typeof AuthenticatedAdminRapportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reclamations': {
      id: '/_authenticated/admin/reclamations'
      path: '/reclamations'
      fullPath: '/admin/reclamations'
      preLoaderRoute: typeof AuthenticatedAdminReclamationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/remboursements': {
      id: '/_authenticated/admin/remboursements'
      path: '/remboursements'
      fullPath: '/admin/remboursements'
      preLoaderRoute: typeof AuthenticatedAdminRemboursementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/retours': {
      id: '/_authenticated/admin/retours'
      path: '/retours'
      fullPath: '/admin/retours'
      preLoaderRoute: typeof AuthenticatedAdminRetoursRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/satisfaction': {
      id: '/_authenticated/admin/satisfaction'
      path: '/satisfaction'
      fullPath: '/admin/satisfaction'
      preLoaderRoute: typeof AuthenticatedAdminSatisfactionRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/securite': {
      id: '/_authenticated/admin/securite'
      path: '/securite'
      fullPath: '/admin/securite'
      preLoaderRoute: typeof AuthenticatedAdminSecuriteRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sla': {
      id: '/_authenticated/admin/sla'
      path: '/sla'
      fullPath: '/admin/sla'
      preLoaderRoute: typeof AuthenticatedAdminSlaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/stats': {
      id: '/_authenticated/admin/stats'
      path: '/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AuthenticatedAdminStatsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/webhooks': {
      id: '/_authenticated/admin/webhooks'
      path: '/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AuthenticatedAdminWebhooksRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/organizations/$orgId': {
      id: '/app/organizations/$orgId'
      path: '/organizations/$orgId'
      fullPath: '/app/organizations/$orgId'
      preLoaderRoute: typeof AppOrganizationsOrgIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organizations/$orgId/billing': {
      id: '/app/organizations/$orgId/billing'
      path: '/billing'
      fullPath: '/app/organizations/$orgId/billing'
      preLoaderRoute: typeof AppOrganizationsOrgIdBillingRouteImport
      parentRoute: typeof AppOrganizationsOrgIdRoute
    }
    '/app/organizations/$orgId/equipment': {
      id: '/app/organizations/$orgId/equipment'
      path: '/equipment'
      fullPath: '/app/organizations/$orgId/equipment'
      preLoaderRoute: typeof AppOrganizationsOrgIdEquipmentRouteImport
      parentRoute: typeof AppOrganizationsOrgIdRoute
    }
    '/app/organizations/$orgId/maintenance': {
      id: '/app/organizations/$orgId/maintenance'
      path: '/maintenance'
      fullPath: '/app/organizations/$orgId/maintenance'
      preLoaderRoute: typeof AppOrganizationsOrgIdMaintenanceRouteImport
      parentRoute: typeof AppOrganizationsOrgIdRoute
    }
    '/app/organizations/$orgId/sites': {
      id: '/app/organizations/$orgId/sites'
      path: '/sites'
      fullPath: '/app/organizations/$orgId/sites'
      preLoaderRoute: typeof AppOrganizationsOrgIdSitesRouteImport
      parentRoute: typeof AppOrganizationsOrgIdRoute
    }
    '/app/organizations/$orgId/tickets': {
      id: '/app/organizations/$orgId/tickets'
      path: '/tickets'
      fullPath: '/app/organizations/$orgId/tickets'
      preLoaderRoute: typeof AppOrganizationsOrgIdTicketsRouteImport
      parentRoute: typeof AppOrganizationsOrgIdRoute
    }
    '/app/organizations/$orgId/equipment/$equipmentId': {
      id: '/app/organizations/$orgId/equipment/$equipmentId'
      path: '/$equipmentId'
      fullPath: '/app/organizations/$orgId/equipment/$equipmentId'
      preLoaderRoute: typeof AppOrganizationsOrgIdEquipmentEquipmentIdRouteImport
      parentRoute: typeof AppOrganizationsOrgIdEquipmentRoute
    }
    '/app/organizations/$orgId/tickets/$ticketId': {
      id: '/app/organizations/$orgId/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/app/organizations/$orgId/tickets/$ticketId'
      preLoaderRoute: typeof AppOrganizationsOrgIdTicketsTicketIdRouteImport
      parentRoute: typeof AppOrganizationsOrgIdTicketsRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAnalyticsAdvancedRoute: typeof AuthenticatedAdminAnalyticsAdvancedRoute
  AuthenticatedAdminAtelierRoute: typeof AuthenticatedAdminAtelierRoute
  AuthenticatedAdminAteliersRoute: typeof AuthenticatedAdminAteliersRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminCaisseRoute: typeof AuthenticatedAdminCaisseRoute
  AuthenticatedAdminCatalogueRoute: typeof AuthenticatedAdminCatalogueRoute
  AuthenticatedAdminChatRoute: typeof AuthenticatedAdminChatRoute
  AuthenticatedAdminCommandesRoute: typeof AuthenticatedAdminCommandesRoute
  AuthenticatedAdminContenuRoute: typeof AuthenticatedAdminContenuRoute
  AuthenticatedAdminDossiersRoute: typeof AuthenticatedAdminDossiersRoute
  AuthenticatedAdminEquipeRoute: typeof AuthenticatedAdminEquipeRoute
  AuthenticatedAdminFeatureFlagsRoute: typeof AuthenticatedAdminFeatureFlagsRoute
  AuthenticatedAdminFournisseursRoute: typeof AuthenticatedAdminFournisseursRoute
  AuthenticatedAdminInventaireRoute: typeof AuthenticatedAdminInventaireRoute
  AuthenticatedAdminKbRoute: typeof AuthenticatedAdminKbRoute
  AuthenticatedAdminKpisRoute: typeof AuthenticatedAdminKpisRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminLivraisonsRoute: typeof AuthenticatedAdminLivraisonsRoute
  AuthenticatedAdminMarketingRoute: typeof AuthenticatedAdminMarketingRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminParrainageRoute: typeof AuthenticatedAdminParrainageRoute
  AuthenticatedAdminRapportsRoute: typeof AuthenticatedAdminRapportsRoute
  AuthenticatedAdminReclamationsRoute: typeof AuthenticatedAdminReclamationsRoute
  AuthenticatedAdminRemboursementsRoute: typeof AuthenticatedAdminRemboursementsRoute
  AuthenticatedAdminRetoursRoute: typeof AuthenticatedAdminRetoursRoute
  AuthenticatedAdminSatisfactionRoute: typeof AuthenticatedAdminSatisfactionRoute
  AuthenticatedAdminSecuriteRoute: typeof AuthenticatedAdminSecuriteRoute
  AuthenticatedAdminSlaRoute: typeof AuthenticatedAdminSlaRoute
  AuthenticatedAdminStatsRoute: typeof AuthenticatedAdminStatsRoute
  AuthenticatedAdminWebhooksRoute: typeof AuthenticatedAdminWebhooksRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminAnalyticsAdvancedRoute:
    AuthenticatedAdminAnalyticsAdvancedRoute,
  AuthenticatedAdminAtelierRoute: AuthenticatedAdminAtelierRoute,
  AuthenticatedAdminAteliersRoute: AuthenticatedAdminAteliersRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminCaisseRoute: AuthenticatedAdminCaisseRoute,
  AuthenticatedAdminCatalogueRoute: AuthenticatedAdminCatalogueRoute,
  AuthenticatedAdminChatRoute: AuthenticatedAdminChatRoute,
  AuthenticatedAdminCommandesRoute: AuthenticatedAdminCommandesRoute,
  AuthenticatedAdminContenuRoute: AuthenticatedAdminContenuRoute,
  AuthenticatedAdminDossiersRoute: AuthenticatedAdminDossiersRoute,
  AuthenticatedAdminEquipeRoute: AuthenticatedAdminEquipeRoute,
  AuthenticatedAdminFeatureFlagsRoute: AuthenticatedAdminFeatureFlagsRoute,
  AuthenticatedAdminFournisseursRoute: AuthenticatedAdminFournisseursRoute,
  AuthenticatedAdminInventaireRoute: AuthenticatedAdminInventaireRoute,
  AuthenticatedAdminKbRoute: AuthenticatedAdminKbRoute,
  AuthenticatedAdminKpisRoute: AuthenticatedAdminKpisRoute,
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
  AuthenticatedAdminLivraisonsRoute: AuthenticatedAdminLivraisonsRoute,
  AuthenticatedAdminMarketingRoute: AuthenticatedAdminMarketingRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminParrainageRoute: AuthenticatedAdminParrainageRoute,
  AuthenticatedAdminRapportsRoute: AuthenticatedAdminRapportsRoute,
  AuthenticatedAdminReclamationsRoute: AuthenticatedAdminReclamationsRoute,
  AuthenticatedAdminRemboursementsRoute: AuthenticatedAdminRemboursementsRoute,
  AuthenticatedAdminRetoursRoute: AuthenticatedAdminRetoursRoute,
  AuthenticatedAdminSatisfactionRoute: AuthenticatedAdminSatisfactionRoute,
  AuthenticatedAdminSecuriteRoute: AuthenticatedAdminSecuriteRoute,
  AuthenticatedAdminSlaRoute: AuthenticatedAdminSlaRoute,
  AuthenticatedAdminStatsRoute: AuthenticatedAdminStatsRoute,
  AuthenticatedAdminWebhooksRoute: AuthenticatedAdminWebhooksRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedMonCompteRoute: typeof AuthenticatedMonCompteRoute
  AuthenticatedReviewsAdminRoute: typeof AuthenticatedReviewsAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedMonCompteRoute: AuthenticatedMonCompteRoute,
  AuthenticatedReviewsAdminRoute: AuthenticatedReviewsAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface LocaleRouteChildren {
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleAvisRoute: typeof LocaleAvisRoute
  LocaleCatalogueRoute: typeof LocaleCatalogueRoute
  LocaleChangelogRoute: typeof LocaleChangelogRoute
  LocaleCheckoutRoute: typeof LocaleCheckoutRoute
  LocaleContactRoute: typeof LocaleContactRoute
  LocaleDevisRoute: typeof LocaleDevisRoute
  LocaleEngagementsRoute: typeof LocaleEngagementsRoute
  LocaleEntreprisesRoute: typeof LocaleEntreprisesRoute
  LocaleFaqRoute: typeof LocaleFaqRoute
  LocaleGarantieRoute: typeof LocaleGarantieRoute
  LocaleGuidesRoute: typeof LocaleGuidesRoute
  LocaleHistoriqueRoute: typeof LocaleHistoriqueRoute
  LocaleMagasinsRoute: typeof LocaleMagasinsRoute
  LocaleMentionsLegalesRoute: typeof LocaleMentionsLegalesRoute
  LocalePanierRoute: typeof LocalePanierRoute
  LocalePromotionsRoute: typeof LocalePromotionsRoute
  LocaleReclamationRoute: typeof LocaleReclamationRoute
  LocaleReconditionnesRoute: typeof LocaleReconditionnesRoute
  LocaleRepriseRoute: typeof LocaleRepriseRoute
  LocaleReservationRoute: typeof LocaleReservationRoute
  LocaleServicesRoute: typeof LocaleServicesRoute
  LocaleSuiviRoute: typeof LocaleSuiviRoute
  LocaleTarifsRoute: typeof LocaleTarifsRoute
  LocaleWorkAtRoute: typeof LocaleWorkAtRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleAppareilSlugRoute: typeof LocaleAppareilSlugRoute
  LocaleBlogSlugRoute: typeof LocaleBlogSlugRoute
  LocaleBoutiqueSlugRoute: typeof LocaleBoutiqueSlugRoute
  LocaleBoutiqueComparerRoute: typeof LocaleBoutiqueComparerRoute
  LocaleQuartiersSlugRoute: typeof LocaleQuartiersSlugRoute
  LocaleReparationsBrandRoute: typeof LocaleReparationsBrandRoute
  LocaleBlogIndexRoute: typeof LocaleBlogIndexRoute
  LocaleBoutiqueIndexRoute: typeof LocaleBoutiqueIndexRoute
  LocaleQuartiersIndexRoute: typeof LocaleQuartiersIndexRoute
  LocaleReparationsIndexRoute: typeof LocaleReparationsIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleAvisRoute: LocaleAvisRoute,
  LocaleCatalogueRoute: LocaleCatalogueRoute,
  LocaleChangelogRoute: LocaleChangelogRoute,
  LocaleCheckoutRoute: LocaleCheckoutRoute,
  LocaleContactRoute: LocaleContactRoute,
  LocaleDevisRoute: LocaleDevisRoute,
  LocaleEngagementsRoute: LocaleEngagementsRoute,
  LocaleEntreprisesRoute: LocaleEntreprisesRoute,
  LocaleFaqRoute: LocaleFaqRoute,
  LocaleGarantieRoute: LocaleGarantieRoute,
  LocaleGuidesRoute: LocaleGuidesRoute,
  LocaleHistoriqueRoute: LocaleHistoriqueRoute,
  LocaleMagasinsRoute: LocaleMagasinsRoute,
  LocaleMentionsLegalesRoute: LocaleMentionsLegalesRoute,
  LocalePanierRoute: LocalePanierRoute,
  LocalePromotionsRoute: LocalePromotionsRoute,
  LocaleReclamationRoute: LocaleReclamationRoute,
  LocaleReconditionnesRoute: LocaleReconditionnesRoute,
  LocaleRepriseRoute: LocaleRepriseRoute,
  LocaleReservationRoute: LocaleReservationRoute,
  LocaleServicesRoute: LocaleServicesRoute,
  LocaleSuiviRoute: LocaleSuiviRoute,
  LocaleTarifsRoute: LocaleTarifsRoute,
  LocaleWorkAtRoute: LocaleWorkAtRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleAppareilSlugRoute: LocaleAppareilSlugRoute,
  LocaleBlogSlugRoute: LocaleBlogSlugRoute,
  LocaleBoutiqueSlugRoute: LocaleBoutiqueSlugRoute,
  LocaleBoutiqueComparerRoute: LocaleBoutiqueComparerRoute,
  LocaleQuartiersSlugRoute: LocaleQuartiersSlugRoute,
  LocaleReparationsBrandRoute: LocaleReparationsBrandRoute,
  LocaleBlogIndexRoute: LocaleBlogIndexRoute,
  LocaleBoutiqueIndexRoute: LocaleBoutiqueIndexRoute,
  LocaleQuartiersIndexRoute: LocaleQuartiersIndexRoute,
  LocaleReparationsIndexRoute: LocaleReparationsIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

interface AppOrganizationsOrgIdEquipmentRouteChildren {
  AppOrganizationsOrgIdEquipmentEquipmentIdRoute: typeof AppOrganizationsOrgIdEquipmentEquipmentIdRoute
}

const AppOrganizationsOrgIdEquipmentRouteChildren: AppOrganizationsOrgIdEquipmentRouteChildren =
  {
    AppOrganizationsOrgIdEquipmentEquipmentIdRoute:
      AppOrganizationsOrgIdEquipmentEquipmentIdRoute,
  }

const AppOrganizationsOrgIdEquipmentRouteWithChildren =
  AppOrganizationsOrgIdEquipmentRoute._addFileChildren(
    AppOrganizationsOrgIdEquipmentRouteChildren,
  )

interface AppOrganizationsOrgIdTicketsRouteChildren {
  AppOrganizationsOrgIdTicketsTicketIdRoute: typeof AppOrganizationsOrgIdTicketsTicketIdRoute
}

const AppOrganizationsOrgIdTicketsRouteChildren: AppOrganizationsOrgIdTicketsRouteChildren =
  {
    AppOrganizationsOrgIdTicketsTicketIdRoute:
      AppOrganizationsOrgIdTicketsTicketIdRoute,
  }

const AppOrganizationsOrgIdTicketsRouteWithChildren =
  AppOrganizationsOrgIdTicketsRoute._addFileChildren(
    AppOrganizationsOrgIdTicketsRouteChildren,
  )

interface AppOrganizationsOrgIdRouteChildren {
  AppOrganizationsOrgIdBillingRoute: typeof AppOrganizationsOrgIdBillingRoute
  AppOrganizationsOrgIdEquipmentRoute: typeof AppOrganizationsOrgIdEquipmentRouteWithChildren
  AppOrganizationsOrgIdMaintenanceRoute: typeof AppOrganizationsOrgIdMaintenanceRoute
  AppOrganizationsOrgIdSitesRoute: typeof AppOrganizationsOrgIdSitesRoute
  AppOrganizationsOrgIdTicketsRoute: typeof AppOrganizationsOrgIdTicketsRouteWithChildren
}

const AppOrganizationsOrgIdRouteChildren: AppOrganizationsOrgIdRouteChildren = {
  AppOrganizationsOrgIdBillingRoute: AppOrganizationsOrgIdBillingRoute,
  AppOrganizationsOrgIdEquipmentRoute:
    AppOrganizationsOrgIdEquipmentRouteWithChildren,
  AppOrganizationsOrgIdMaintenanceRoute: AppOrganizationsOrgIdMaintenanceRoute,
  AppOrganizationsOrgIdSitesRoute: AppOrganizationsOrgIdSitesRoute,
  AppOrganizationsOrgIdTicketsRoute:
    AppOrganizationsOrgIdTicketsRouteWithChildren,
}

const AppOrganizationsOrgIdRouteWithChildren =
  AppOrganizationsOrgIdRoute._addFileChildren(
    AppOrganizationsOrgIdRouteChildren,
  )

interface AppRouteChildren {
  AppGroupDashboardRoute: typeof AppGroupDashboardRoute
  AppScanRoute: typeof AppScanRoute
  AppIndexRoute: typeof AppIndexRoute
  AppOrganizationsOrgIdRoute: typeof AppOrganizationsOrgIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppGroupDashboardRoute: AppGroupDashboardRoute,
  AppScanRoute: AppScanRoute,
  AppIndexRoute: AppIndexRoute,
  AppOrganizationsOrgIdRoute: AppOrganizationsOrgIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LocaleRoute: LocaleRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  DemoRoute: DemoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiCronRemindersRoute: ApiCronRemindersRoute,
  ApiDocsRoute: ApiDocsRoute,
  ApiFedapayWebhookRoute: ApiFedapayWebhookRoute,
  ApiFlutterwaveWebhookRoute: ApiFlutterwaveWebhookRoute,
  ApiHealthzRoute: ApiHealthzRoute,
  ApiIcalRoute: ApiIcalRoute,
  ApiKkiapayWebhookRoute: ApiKkiapayWebhookRoute,
  ApiPushSubscribeRoute: ApiPushSubscribeRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
