/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AvisRouteImport } from './routes/avis'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DevisRouteImport } from './routes/devis'
import { Route as EntreprisesRouteImport } from './routes/entreprises'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GarantieRouteImport } from './routes/garantie'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as RepriseRouteImport } from './routes/reprise'
import { Route as ReservationRouteImport } from './routes/reservation'
import { Route as SuiviRouteImport } from './routes/suivi'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMonCompteRouteImport } from './routes/_authenticated/mon-compte'
import { Route as AppareilSlugRouteImport } from './routes/appareil.$slug'
import { Route as BoutiqueIndexRouteImport } from './routes/boutique.index'
import { Route as BoutiqueSlugRouteImport } from './routes/boutique.$slug'
import { Route as ReparationsIndexRouteImport } from './routes/reparations.index'
import { Route as ReparationsBrandRouteImport } from './routes/reparations.$brand'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisRoute = AvisRouteImport.update({
  id: '/avis',
  path: '/avis',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DevisRoute = DevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => rootRouteImport,
} as any)
const EntreprisesRoute = EntreprisesRouteImport.update({
  id: '/entreprises',
  path: '/entreprises',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GarantieRoute = GarantieRouteImport.update({
  id: '/garantie',
  path: '/garantie',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const RepriseRoute = RepriseRouteImport.update({
  id: '/reprise',
  path: '/reprise',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationRoute = ReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const SuiviRoute = SuiviRouteImport.update({
  id: '/suivi',
  path: '/suivi',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonCompteRoute = AuthenticatedMonCompteRouteImport.update({
  id: '/mon-compte',
  path: '/mon-compte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AppareilSlugRoute = AppareilSlugRouteImport.update({
  id: '/appareil/$slug',
  path: '/appareil/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueIndexRoute = BoutiqueIndexRouteImport.update({
  id: '/boutique/',
  path: '/boutique/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueSlugRoute = BoutiqueSlugRouteImport.update({
  id: '/boutique/$slug',
  path: '/boutique/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReparationsIndexRoute = ReparationsIndexRouteImport.update({
  id: '/reparations/',
  path: '/reparations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReparationsBrandRoute = ReparationsBrandRouteImport.update({
  id: '/reparations/$brand',
  path: '/reparations/$brand',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avis': typeof AvisRoute
  '/contact': typeof ContactRoute
  '/devis': typeof DevisRoute
  '/entreprises': typeof EntreprisesRoute
  '/faq': typeof FaqRoute
  '/garantie': typeof GarantieRoute
  '/panier': typeof PanierRoute
  '/reprise': typeof RepriseRoute
  '/reservation': typeof ReservationRoute
  '/suivi': typeof SuiviRoute
  '/tarifs': typeof TarifsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/mon-compte': typeof AuthenticatedMonCompteRoute
  '/appareil/$slug': typeof AppareilSlugRoute
  '/boutique/$slug': typeof BoutiqueSlugRoute
  '/reparations/$brand': typeof ReparationsBrandRoute
  '/boutique/': typeof BoutiqueIndexRoute
  '/reparations/': typeof ReparationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avis': typeof AvisRoute
  '/contact': typeof ContactRoute
  '/devis': typeof DevisRoute
  '/entreprises': typeof EntreprisesRoute
  '/faq': typeof FaqRoute
  '/garantie': typeof GarantieRoute
  '/panier': typeof PanierRoute
  '/reprise': typeof RepriseRoute
  '/reservation': typeof ReservationRoute
  '/suivi': typeof SuiviRoute
  '/tarifs': typeof TarifsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/mon-compte': typeof AuthenticatedMonCompteRoute
  '/appareil/$slug': typeof AppareilSlugRoute
  '/boutique/$slug': typeof BoutiqueSlugRoute
  '/reparations/$brand': typeof ReparationsBrandRoute
  '/boutique': typeof BoutiqueIndexRoute
  '/reparations': typeof ReparationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/avis': typeof AvisRoute
  '/contact': typeof ContactRoute
  '/devis': typeof DevisRoute
  '/entreprises': typeof EntreprisesRoute
  '/faq': typeof FaqRoute
  '/garantie': typeof GarantieRoute
  '/panier': typeof PanierRoute
  '/reprise': typeof RepriseRoute
  '/reservation': typeof ReservationRoute
  '/suivi': typeof SuiviRoute
  '/tarifs': typeof TarifsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/mon-compte': typeof AuthenticatedMonCompteRoute
  '/appareil/$slug': typeof AppareilSlugRoute
  '/boutique/$slug': typeof BoutiqueSlugRoute
  '/reparations/$brand': typeof ReparationsBrandRoute
  '/boutique/': typeof BoutiqueIndexRoute
  '/reparations/': typeof ReparationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/avis'
    | '/contact'
    | '/devis'
    | '/entreprises'
    | '/faq'
    | '/garantie'
    | '/panier'
    | '/reprise'
    | '/reservation'
    | '/suivi'
    | '/tarifs'
    | '/admin'
    | '/mon-compte'
    | '/appareil/$slug'
    | '/boutique/$slug'
    | '/reparations/$brand'
    | '/boutique/'
    | '/reparations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/avis'
    | '/contact'
    | '/devis'
    | '/entreprises'
    | '/faq'
    | '/garantie'
    | '/panier'
    | '/reprise'
    | '/reservation'
    | '/suivi'
    | '/tarifs'
    | '/admin'
    | '/mon-compte'
    | '/appareil/$slug'
    | '/boutique/$slug'
    | '/reparations/$brand'
    | '/boutique'
    | '/reparations'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/avis'
    | '/contact'
    | '/devis'
    | '/entreprises'
    | '/faq'
    | '/garantie'
    | '/panier'
    | '/reprise'
    | '/reservation'
    | '/suivi'
    | '/tarifs'
    | '/_authenticated/admin'
    | '/_authenticated/mon-compte'
    | '/appareil/$slug'
    | '/boutique/$slug'
    | '/reparations/$brand'
    | '/boutique/'
    | '/reparations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AvisRoute: typeof AvisRoute
  ContactRoute: typeof ContactRoute
  DevisRoute: typeof DevisRoute
  EntreprisesRoute: typeof EntreprisesRoute
  FaqRoute: typeof FaqRoute
  GarantieRoute: typeof GarantieRoute
  PanierRoute: typeof PanierRoute
  RepriseRoute: typeof RepriseRoute
  ReservationRoute: typeof ReservationRoute
  SuiviRoute: typeof SuiviRoute
  TarifsRoute: typeof TarifsRoute
  AppareilSlugRoute: typeof AppareilSlugRoute
  BoutiqueSlugRoute: typeof BoutiqueSlugRoute
  ReparationsBrandRoute: typeof ReparationsBrandRoute
  BoutiqueIndexRoute: typeof BoutiqueIndexRoute
  ReparationsIndexRoute: typeof ReparationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avis': {
      id: '/avis'
      path: '/avis'
      fullPath: '/avis'
      preLoaderRoute: typeof AvisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis': {
      id: '/devis'
      path: '/devis'
      fullPath: '/devis'
      preLoaderRoute: typeof DevisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entreprises': {
      id: '/entreprises'
      path: '/entreprises'
      fullPath: '/entreprises'
      preLoaderRoute: typeof EntreprisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garantie': {
      id: '/garantie'
      path: '/garantie'
      fullPath: '/garantie'
      preLoaderRoute: typeof GarantieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reprise': {
      id: '/reprise'
      path: '/reprise'
      fullPath: '/reprise'
      preLoaderRoute: typeof RepriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation': {
      id: '/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof ReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suivi': {
      id: '/suivi'
      path: '/suivi'
      fullPath: '/suivi'
      preLoaderRoute: typeof SuiviRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon-compte': {
      id: '/_authenticated/mon-compte'
      path: '/mon-compte'
      fullPath: '/mon-compte'
      preLoaderRoute: typeof AuthenticatedMonCompteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/appareil/$slug': {
      id: '/appareil/$slug'
      path: '/appareil/$slug'
      fullPath: '/appareil/$slug'
      preLoaderRoute: typeof AppareilSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique/': {
      id: '/boutique/'
      path: '/boutique'
      fullPath: '/boutique/'
      preLoaderRoute: typeof BoutiqueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique/$slug': {
      id: '/boutique/$slug'
      path: '/boutique/$slug'
      fullPath: '/boutique/$slug'
      preLoaderRoute: typeof BoutiqueSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reparations/': {
      id: '/reparations/'
      path: '/reparations'
      fullPath: '/reparations/'
      preLoaderRoute: typeof ReparationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reparations/$brand': {
      id: '/reparations/$brand'
      path: '/reparations/$brand'
      fullPath: '/reparations/$brand'
      preLoaderRoute: typeof ReparationsBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedMonCompteRoute: typeof AuthenticatedMonCompteRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedMonCompteRoute: AuthenticatedMonCompteRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AvisRoute: AvisRoute,
  ContactRoute: ContactRoute,
  DevisRoute: DevisRoute,
  EntreprisesRoute: EntreprisesRoute,
  FaqRoute: FaqRoute,
  GarantieRoute: GarantieRoute,
  PanierRoute: PanierRoute,
  RepriseRoute: RepriseRoute,
  ReservationRoute: ReservationRoute,
  SuiviRoute: SuiviRoute,
  TarifsRoute: TarifsRoute,
  AppareilSlugRoute: AppareilSlugRoute,
  BoutiqueSlugRoute: BoutiqueSlugRoute,
  ReparationsBrandRoute: ReparationsBrandRoute,
  BoutiqueIndexRoute: BoutiqueIndexRoute,
  ReparationsIndexRoute: ReparationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
