/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleAvisRouteImport } from './routes/$locale/avis'
import { Route as LocaleCatalogueRouteImport } from './routes/$locale/catalogue'
import { Route as LocaleContactRouteImport } from './routes/$locale/contact'
import { Route as LocaleDevisRouteImport } from './routes/$locale/devis'
import { Route as LocaleEntreprisesRouteImport } from './routes/$locale/entreprises'
import { Route as LocaleFaqRouteImport } from './routes/$locale/faq'
import { Route as LocaleGarantieRouteImport } from './routes/$locale/garantie'
import { Route as LocaleMagasinsRouteImport } from './routes/$locale/magasins'
import { Route as LocaleMentionsLegalesRouteImport } from './routes/$locale/mentions-legales'
import { Route as LocalePanierRouteImport } from './routes/$locale/panier'
import { Route as LocalePromotionsRouteImport } from './routes/$locale/promotions'
import { Route as LocaleRepriseRouteImport } from './routes/$locale/reprise'
import { Route as LocaleReservationRouteImport } from './routes/$locale/reservation'
import { Route as LocaleServicesRouteImport } from './routes/$locale/services'
import { Route as LocaleSuiviRouteImport } from './routes/$locale/suivi'
import { Route as LocaleTarifsRouteImport } from './routes/$locale/tarifs'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMonCompteRouteImport } from './routes/_authenticated/mon-compte'
import { Route as ApiFlutterwaveWebhookRouteImport } from './routes/api.flutterwave-webhook'
import { Route as ApiHealthzRouteImport } from './routes/api.healthz'
import { Route as LocaleAppareilSlugRouteImport } from './routes/$locale/appareil.$slug'
import { Route as LocaleBlogIndexRouteImport } from './routes/$locale/blog.index'
import { Route as LocaleBlogSlugRouteImport } from './routes/$locale/blog.$slug'
import { Route as LocaleBoutiqueIndexRouteImport } from './routes/$locale/boutique.index'
import { Route as LocaleBoutiqueSlugRouteImport } from './routes/$locale/boutique.$slug'
import { Route as LocaleReparationsIndexRouteImport } from './routes/$locale/reparations.index'
import { Route as LocaleReparationsBrandRouteImport } from './routes/$locale/reparations.$brand'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAvisRoute = LocaleAvisRouteImport.update({
  id: '/avis',
  path: '/avis',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCatalogueRoute = LocaleCatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleContactRoute = LocaleContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleDevisRoute = LocaleDevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleEntreprisesRoute = LocaleEntreprisesRouteImport.update({
  id: '/entreprises',
  path: '/entreprises',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleFaqRoute = LocaleFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleGarantieRoute = LocaleGarantieRouteImport.update({
  id: '/garantie',
  path: '/garantie',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleMagasinsRoute = LocaleMagasinsRouteImport.update({
  id: '/magasins',
  path: '/magasins',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleMentionsLegalesRoute = LocaleMentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePanierRoute = LocalePanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePromotionsRoute = LocalePromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleRepriseRoute = LocaleRepriseRouteImport.update({
  id: '/reprise',
  path: '/reprise',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleReservationRoute = LocaleReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleServicesRoute = LocaleServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSuiviRoute = LocaleSuiviRouteImport.update({
  id: '/suivi',
  path: '/suivi',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleTarifsRoute = LocaleTarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => LocaleRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonCompteRoute = AuthenticatedMonCompteRouteImport.update({
  id: '/mon-compte',
  path: '/mon-compte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiFlutterwaveWebhookRoute = ApiFlutterwaveWebhookRouteImport.update({
  id: '/api/flutterwave-webhook',
  path: '/api/flutterwave-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthzRoute = ApiHealthzRouteImport.update({
  id: '/api/healthz',
  path: '/api/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleAppareilSlugRoute = LocaleAppareilSlugRouteImport.update({
  id: '/appareil/$slug',
  path: '/appareil/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBlogIndexRoute = LocaleBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBlogSlugRoute = LocaleBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBoutiqueIndexRoute = LocaleBoutiqueIndexRouteImport.update({
  id: '/boutique/',
  path: '/boutique/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBoutiqueSlugRoute = LocaleBoutiqueSlugRouteImport.update({
  id: '/boutique/$slug',
  path: '/boutique/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleReparationsIndexRoute = LocaleReparationsIndexRouteImport.update({
  id: '/reparations/',
  path: '/reparations/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleReparationsBrandRoute = LocaleReparationsBrandRouteImport.update({
  id: '/reparations/$brand',
  path: '/reparations/$brand',
  getParentRoute: () => LocaleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/avis': typeof LocaleAvisRoute
  '/$locale/catalogue': typeof LocaleCatalogueRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/devis': typeof LocaleDevisRoute
  '/$locale/entreprises': typeof LocaleEntreprisesRoute
  '/$locale/faq': typeof LocaleFaqRoute
  '/$locale/garantie': typeof LocaleGarantieRoute
  '/$locale/magasins': typeof LocaleMagasinsRoute
  '/$locale/mentions-legales': typeof LocaleMentionsLegalesRoute
  '/$locale/panier': typeof LocalePanierRoute
  '/$locale/promotions': typeof LocalePromotionsRoute
  '/$locale/reprise': typeof LocaleRepriseRoute
  '/$locale/reservation': typeof LocaleReservationRoute
  '/$locale/services': typeof LocaleServicesRoute
  '/$locale/suivi': typeof LocaleSuiviRoute
  '/$locale/tarifs': typeof LocaleTarifsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/mon-compte': typeof AuthenticatedMonCompteRoute
  '/api/flutterwave-webhook': typeof ApiFlutterwaveWebhookRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/appareil/$slug': typeof LocaleAppareilSlugRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/boutique/$slug': typeof LocaleBoutiqueSlugRoute
  '/$locale/reparations/$brand': typeof LocaleReparationsBrandRoute
  '/$locale/blog/': typeof LocaleBlogIndexRoute
  '/$locale/boutique/': typeof LocaleBoutiqueIndexRoute
  '/$locale/reparations/': typeof LocaleReparationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/avis': typeof LocaleAvisRoute
  '/$locale/catalogue': typeof LocaleCatalogueRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/devis': typeof LocaleDevisRoute
  '/$locale/entreprises': typeof LocaleEntreprisesRoute
  '/$locale/faq': typeof LocaleFaqRoute
  '/$locale/garantie': typeof LocaleGarantieRoute
  '/$locale/magasins': typeof LocaleMagasinsRoute
  '/$locale/mentions-legales': typeof LocaleMentionsLegalesRoute
  '/$locale/panier': typeof LocalePanierRoute
  '/$locale/promotions': typeof LocalePromotionsRoute
  '/$locale/reprise': typeof LocaleRepriseRoute
  '/$locale/reservation': typeof LocaleReservationRoute
  '/$locale/services': typeof LocaleServicesRoute
  '/$locale/suivi': typeof LocaleSuiviRoute
  '/$locale/tarifs': typeof LocaleTarifsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/mon-compte': typeof AuthenticatedMonCompteRoute
  '/api/flutterwave-webhook': typeof ApiFlutterwaveWebhookRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/appareil/$slug': typeof LocaleAppareilSlugRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/boutique/$slug': typeof LocaleBoutiqueSlugRoute
  '/$locale/reparations/$brand': typeof LocaleReparationsBrandRoute
  '/$locale/blog': typeof LocaleBlogIndexRoute
  '/$locale/boutique': typeof LocaleBoutiqueIndexRoute
  '/$locale/reparations': typeof LocaleReparationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$locale': typeof LocaleRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/avis': typeof LocaleAvisRoute
  '/$locale/catalogue': typeof LocaleCatalogueRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/devis': typeof LocaleDevisRoute
  '/$locale/entreprises': typeof LocaleEntreprisesRoute
  '/$locale/faq': typeof LocaleFaqRoute
  '/$locale/garantie': typeof LocaleGarantieRoute
  '/$locale/magasins': typeof LocaleMagasinsRoute
  '/$locale/mentions-legales': typeof LocaleMentionsLegalesRoute
  '/$locale/panier': typeof LocalePanierRoute
  '/$locale/promotions': typeof LocalePromotionsRoute
  '/$locale/reprise': typeof LocaleRepriseRoute
  '/$locale/reservation': typeof LocaleReservationRoute
  '/$locale/services': typeof LocaleServicesRoute
  '/$locale/suivi': typeof LocaleSuiviRoute
  '/$locale/tarifs': typeof LocaleTarifsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/mon-compte': typeof AuthenticatedMonCompteRoute
  '/api/flutterwave-webhook': typeof ApiFlutterwaveWebhookRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/appareil/$slug': typeof LocaleAppareilSlugRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/boutique/$slug': typeof LocaleBoutiqueSlugRoute
  '/$locale/reparations/$brand': typeof LocaleReparationsBrandRoute
  '/$locale/blog/': typeof LocaleBlogIndexRoute
  '/$locale/boutique/': typeof LocaleBoutiqueIndexRoute
  '/$locale/reparations/': typeof LocaleReparationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/auth'
    | '/sitemap.xml'
    | '/$locale/avis'
    | '/$locale/catalogue'
    | '/$locale/contact'
    | '/$locale/devis'
    | '/$locale/entreprises'
    | '/$locale/faq'
    | '/$locale/garantie'
    | '/$locale/magasins'
    | '/$locale/mentions-legales'
    | '/$locale/panier'
    | '/$locale/promotions'
    | '/$locale/reprise'
    | '/$locale/reservation'
    | '/$locale/services'
    | '/$locale/suivi'
    | '/$locale/tarifs'
    | '/admin'
    | '/mon-compte'
    | '/api/flutterwave-webhook'
    | '/api/healthz'
    | '/$locale/'
    | '/$locale/appareil/$slug'
    | '/$locale/blog/$slug'
    | '/$locale/boutique/$slug'
    | '/$locale/reparations/$brand'
    | '/$locale/blog/'
    | '/$locale/boutique/'
    | '/$locale/reparations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/$locale/avis'
    | '/$locale/catalogue'
    | '/$locale/contact'
    | '/$locale/devis'
    | '/$locale/entreprises'
    | '/$locale/faq'
    | '/$locale/garantie'
    | '/$locale/magasins'
    | '/$locale/mentions-legales'
    | '/$locale/panier'
    | '/$locale/promotions'
    | '/$locale/reprise'
    | '/$locale/reservation'
    | '/$locale/services'
    | '/$locale/suivi'
    | '/$locale/tarifs'
    | '/admin'
    | '/mon-compte'
    | '/api/flutterwave-webhook'
    | '/api/healthz'
    | '/$locale'
    | '/$locale/appareil/$slug'
    | '/$locale/blog/$slug'
    | '/$locale/boutique/$slug'
    | '/$locale/reparations/$brand'
    | '/$locale/blog'
    | '/$locale/boutique'
    | '/$locale/reparations'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$locale'
    | '/auth'
    | '/sitemap.xml'
    | '/$locale/avis'
    | '/$locale/catalogue'
    | '/$locale/contact'
    | '/$locale/devis'
    | '/$locale/entreprises'
    | '/$locale/faq'
    | '/$locale/garantie'
    | '/$locale/magasins'
    | '/$locale/mentions-legales'
    | '/$locale/panier'
    | '/$locale/promotions'
    | '/$locale/reprise'
    | '/$locale/reservation'
    | '/$locale/services'
    | '/$locale/suivi'
    | '/$locale/tarifs'
    | '/_authenticated/admin'
    | '/_authenticated/mon-compte'
    | '/api/flutterwave-webhook'
    | '/api/healthz'
    | '/$locale/'
    | '/$locale/appareil/$slug'
    | '/$locale/blog/$slug'
    | '/$locale/boutique/$slug'
    | '/$locale/reparations/$brand'
    | '/$locale/blog/'
    | '/$locale/boutique/'
    | '/$locale/reparations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LocaleRoute: typeof LocaleRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiFlutterwaveWebhookRoute: typeof ApiFlutterwaveWebhookRoute
  ApiHealthzRoute: typeof ApiHealthzRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/avis': {
      id: '/$locale/avis'
      path: '/avis'
      fullPath: '/$locale/avis'
      preLoaderRoute: typeof LocaleAvisRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/catalogue': {
      id: '/$locale/catalogue'
      path: '/catalogue'
      fullPath: '/$locale/catalogue'
      preLoaderRoute: typeof LocaleCatalogueRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/contact': {
      id: '/$locale/contact'
      path: '/contact'
      fullPath: '/$locale/contact'
      preLoaderRoute: typeof LocaleContactRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/devis': {
      id: '/$locale/devis'
      path: '/devis'
      fullPath: '/$locale/devis'
      preLoaderRoute: typeof LocaleDevisRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/entreprises': {
      id: '/$locale/entreprises'
      path: '/entreprises'
      fullPath: '/$locale/entreprises'
      preLoaderRoute: typeof LocaleEntreprisesRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/faq': {
      id: '/$locale/faq'
      path: '/faq'
      fullPath: '/$locale/faq'
      preLoaderRoute: typeof LocaleFaqRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/garantie': {
      id: '/$locale/garantie'
      path: '/garantie'
      fullPath: '/$locale/garantie'
      preLoaderRoute: typeof LocaleGarantieRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/magasins': {
      id: '/$locale/magasins'
      path: '/magasins'
      fullPath: '/$locale/magasins'
      preLoaderRoute: typeof LocaleMagasinsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/mentions-legales': {
      id: '/$locale/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/$locale/mentions-legales'
      preLoaderRoute: typeof LocaleMentionsLegalesRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/panier': {
      id: '/$locale/panier'
      path: '/panier'
      fullPath: '/$locale/panier'
      preLoaderRoute: typeof LocalePanierRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/promotions': {
      id: '/$locale/promotions'
      path: '/promotions'
      fullPath: '/$locale/promotions'
      preLoaderRoute: typeof LocalePromotionsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/reprise': {
      id: '/$locale/reprise'
      path: '/reprise'
      fullPath: '/$locale/reprise'
      preLoaderRoute: typeof LocaleRepriseRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/reservation': {
      id: '/$locale/reservation'
      path: '/reservation'
      fullPath: '/$locale/reservation'
      preLoaderRoute: typeof LocaleReservationRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/services': {
      id: '/$locale/services'
      path: '/services'
      fullPath: '/$locale/services'
      preLoaderRoute: typeof LocaleServicesRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/suivi': {
      id: '/$locale/suivi'
      path: '/suivi'
      fullPath: '/$locale/suivi'
      preLoaderRoute: typeof LocaleSuiviRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/tarifs': {
      id: '/$locale/tarifs'
      path: '/tarifs'
      fullPath: '/$locale/tarifs'
      preLoaderRoute: typeof LocaleTarifsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon-compte': {
      id: '/_authenticated/mon-compte'
      path: '/mon-compte'
      fullPath: '/mon-compte'
      preLoaderRoute: typeof AuthenticatedMonCompteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/flutterwave-webhook': {
      id: '/api/flutterwave-webhook'
      path: '/api/flutterwave-webhook'
      fullPath: '/api/flutterwave-webhook'
      preLoaderRoute: typeof ApiFlutterwaveWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/healthz': {
      id: '/api/healthz'
      path: '/api/healthz'
      fullPath: '/api/healthz'
      preLoaderRoute: typeof ApiHealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/appareil/$slug': {
      id: '/$locale/appareil/$slug'
      path: '/appareil/$slug'
      fullPath: '/$locale/appareil/$slug'
      preLoaderRoute: typeof LocaleAppareilSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/blog/': {
      id: '/$locale/blog/'
      path: '/blog'
      fullPath: '/$locale/blog/'
      preLoaderRoute: typeof LocaleBlogIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/blog/$slug': {
      id: '/$locale/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/$locale/blog/$slug'
      preLoaderRoute: typeof LocaleBlogSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/boutique/': {
      id: '/$locale/boutique/'
      path: '/boutique'
      fullPath: '/$locale/boutique/'
      preLoaderRoute: typeof LocaleBoutiqueIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/boutique/$slug': {
      id: '/$locale/boutique/$slug'
      path: '/boutique/$slug'
      fullPath: '/$locale/boutique/$slug'
      preLoaderRoute: typeof LocaleBoutiqueSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/reparations/': {
      id: '/$locale/reparations/'
      path: '/reparations'
      fullPath: '/$locale/reparations/'
      preLoaderRoute: typeof LocaleReparationsIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/reparations/$brand': {
      id: '/$locale/reparations/$brand'
      path: '/reparations/$brand'
      fullPath: '/$locale/reparations/$brand'
      preLoaderRoute: typeof LocaleReparationsBrandRouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedMonCompteRoute: typeof AuthenticatedMonCompteRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedMonCompteRoute: AuthenticatedMonCompteRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface LocaleRouteChildren {
  LocaleAvisRoute: typeof LocaleAvisRoute
  LocaleCatalogueRoute: typeof LocaleCatalogueRoute
  LocaleContactRoute: typeof LocaleContactRoute
  LocaleDevisRoute: typeof LocaleDevisRoute
  LocaleEntreprisesRoute: typeof LocaleEntreprisesRoute
  LocaleFaqRoute: typeof LocaleFaqRoute
  LocaleGarantieRoute: typeof LocaleGarantieRoute
  LocaleMagasinsRoute: typeof LocaleMagasinsRoute
  LocaleMentionsLegalesRoute: typeof LocaleMentionsLegalesRoute
  LocalePanierRoute: typeof LocalePanierRoute
  LocalePromotionsRoute: typeof LocalePromotionsRoute
  LocaleRepriseRoute: typeof LocaleRepriseRoute
  LocaleReservationRoute: typeof LocaleReservationRoute
  LocaleServicesRoute: typeof LocaleServicesRoute
  LocaleSuiviRoute: typeof LocaleSuiviRoute
  LocaleTarifsRoute: typeof LocaleTarifsRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleAppareilSlugRoute: typeof LocaleAppareilSlugRoute
  LocaleBlogSlugRoute: typeof LocaleBlogSlugRoute
  LocaleBoutiqueSlugRoute: typeof LocaleBoutiqueSlugRoute
  LocaleReparationsBrandRoute: typeof LocaleReparationsBrandRoute
  LocaleBlogIndexRoute: typeof LocaleBlogIndexRoute
  LocaleBoutiqueIndexRoute: typeof LocaleBoutiqueIndexRoute
  LocaleReparationsIndexRoute: typeof LocaleReparationsIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAvisRoute: LocaleAvisRoute,
  LocaleCatalogueRoute: LocaleCatalogueRoute,
  LocaleContactRoute: LocaleContactRoute,
  LocaleDevisRoute: LocaleDevisRoute,
  LocaleEntreprisesRoute: LocaleEntreprisesRoute,
  LocaleFaqRoute: LocaleFaqRoute,
  LocaleGarantieRoute: LocaleGarantieRoute,
  LocaleMagasinsRoute: LocaleMagasinsRoute,
  LocaleMentionsLegalesRoute: LocaleMentionsLegalesRoute,
  LocalePanierRoute: LocalePanierRoute,
  LocalePromotionsRoute: LocalePromotionsRoute,
  LocaleRepriseRoute: LocaleRepriseRoute,
  LocaleReservationRoute: LocaleReservationRoute,
  LocaleServicesRoute: LocaleServicesRoute,
  LocaleSuiviRoute: LocaleSuiviRoute,
  LocaleTarifsRoute: LocaleTarifsRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleAppareilSlugRoute: LocaleAppareilSlugRoute,
  LocaleBlogSlugRoute: LocaleBlogSlugRoute,
  LocaleBoutiqueSlugRoute: LocaleBoutiqueSlugRoute,
  LocaleReparationsBrandRoute: LocaleReparationsBrandRoute,
  LocaleBlogIndexRoute: LocaleBlogIndexRoute,
  LocaleBoutiqueIndexRoute: LocaleBoutiqueIndexRoute,
  LocaleReparationsIndexRoute: LocaleReparationsIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LocaleRoute: LocaleRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiFlutterwaveWebhookRoute: ApiFlutterwaveWebhookRoute,
  ApiHealthzRoute: ApiHealthzRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
